### ISSUE TITLE
Automerge with CODEOWNERS

### ISSUE THREAD

**Issue by gauntface** [renovatebot/config-help#114]
I have a number of repos that have CODEOWNERS set up so I get tagged in on any PR's and ideally I'd like to keep that while also allowing renovate to auto-merge PRs that have successful status checks.

At the moment all of the PR's that have been raised on https://github.com/gauntface/hopin-web-build-tools/pulls aren't getting merged once they've passed. My hunch is that it's due to the reviewer being added, but I'm not sure.

Is there anyway to have the setup described above?

**Comment by rarkins** [comment]
Taking a look at your `renovate.json` it appears that you don't have `assignees` configured. Do I understand correctly that you're suggesting Renovate could use the CODEOWNERS logic to decide who to assign automatically?

FYI though, right now Renovate's behaviour is *not* to assign PRs if they are to be automerged. This was requested early on because people felt like it reduced the noise a little. So if you want assigning *and* automerging then that might also require a new option to force on.

The final topic is why Renovate isn't automerging when configured to do so? Without any PRs currently open it restricts my ability to guess, however from the merged ones it looks like the automerge setting was detected correctly:
![image](https://user-images.githubusercontent.com/6311784/46920767-58e1dd80-cff3-11e8-8c92-d2a082bc07b8.png)

Do you have an CI/tests enabled for that repo? It would be either that, or because you have set up some form of branch protection that blocks Renovate, such as required reviews, or approved committers to master, etc.

**Comment by rarkins** [comment]
Right now Renovate is oblivious to CODEOWNERS. I see that PRs are having you added as Reviewer though but that must be something automatic as Renovate is not doing that explicitly. I suppose there's a possibility that GitHub adds an automatic restriction that the codeowner must approve the PR before it is allowed to be merged.

One other possibility if the automerging used to work but recently stopped is that it's because of TravisCI's deprecation of commit statuses in favour of check runs.

As you suggest though, please alert me the next time there's a PR so that I can dig deeper.

**Comment by gauntface** [comment]
Ok so here is an example PR that I would have thought could be auto-merged: https://github.com/gauntface/hopin-web-build-tools/pull/27

**Comment by gauntface** [comment]
well I'll be damned. ok I take it all back :) sorry for the noise and thank you for all your help

**Comment by rarkins** [comment]
Well I’m not convinced.. some of those old ones definitely look like they stayed open without automerging. Of course, please reopen or raise a new issue if it reoccurs.

**Comment by gauntface** [comment]
So I've found another one that is sticking around: https://github.com/gauntface/hopin-static-site-gen

**Comment by gauntface** [comment]
I thought I had another one but it actually merged in the end - starting to think coveralls is just being slow / a bad actor in this case.

**Comment by rarkins** [comment]
@gauntface 	that PR was actually just waiting for its next scheduled turn. FYI, we don't current run immediately on "green" because GitHub's webhooks do not give enough information to know for sure if a PR is ready for merge. i.e. it tells us that *a* status or check run completed, but not the combined status. So to run "immediately" would mean a lot of inefficient runs where:

- We receive a webhook that something is passed
- We run, "just in case"
- GitHub tells us that actually there's other checks still waiting\
- We actually do nothing

Expect this to change once GitHub does, but for now it just means that automerging takes up to an hour or so depending on when the next scheduled run occurs.

**Comment by msimperi** [comment]
I'm wondering if this CODEOWNERS app/renovate-approve still works as a correct approach. If I add renovate-approve to the CODEOWNERS list, GitHub does not add anyone as reviewer for a PR. Can you verify that this still works?

**Comment by jfairley** [comment]
My issue sounds the same as @msimperi.

Without automerge, I had a `CODEOWNERS` file like:

```
*             @adcellerant/app
```

Because I want automerge, I updated it like:


```
*             @adcellerant/app
package.json  @adcellerant/app app/renovate-approve
yarn.lock     @adcellerant/app app/renovate-approve
