### ISSUE TITLE
Respect Semver

### ISSUE THREAD

**Issue by chrisforrette** [renovatebot/config-help#126]
I'm confused by how Renovate works with semver and I simply want it to treat my repos with the same approach to it that NPM uses it (there's a semver calculator [here](https://semver.npmjs.com/)). My understanding is this:

* "1.0.0": This is a pinned version, don't touch it
* "^1.0.0": Update if there's a new minor version available, but don't upgrade beyond 1.x
* "~1.0.0": Update if there's a new patch version available, but don't upgrade beyond 1.0.x

In a current repo, I have the initial PR open to configure renovate and I've tried changing `rangeStrategy` to `bump`, `pin`, and `replace`, and all of them seem to want to update in the same way. In all cases, for example, I have `webpack` in my `devDependencies` pinned to 3.8.1 (`"webpack": "3.8.1"`) and it's trying to upgrade to v4 in all cases. This is assuming that the description in the PR gets updated any time I'm changing `renovate.json` in the initial PR branch and pushing it up.

I am similarly confused by the [`preserveSemverRanges` preset](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-default/package.json#L44), which simply sets `rangeStrategy` to `replace`, which actually seems to be the most aggressive update strategy.

So I'm not sure if something is wrong with my PR or if my understanding of semver is misaligned with the way Renovate treats it.

**Comment by rarkins** [comment]
Please take a read of https://renovatebot.com/docs/dependency-pinning/ and then let me know if you're running an application, or a library.

**Comment by chrisforrette** [comment]
@rarkins OK, I read through that, but it doesn't really clarify why my the initial Renovate PR is wanting to do rampant major version updates. I currently have my `rangeStrategy` set to `bump`, which seems like it would respect semver and leave pinned versions alone, but that doesn't seem to be the case.

As for application vs. library, this project in particular is an application but I will be configuring for a few libraries as well.

**Comment by rarkins** [comment]
First thing to know is that `rangeStrategy` applies only when the current/existing value is a range. If the existing value is an exact version like `3.8.1` then `rangeStrategy` doesn't apply.

Next thing to remember is that Renovate's purpose is to propose updates for your versions, not leave them alone. For an application, all your versions ideally should be pinned, and Renovate should be telling you whenever there is an update available. If you want to ignore updates for a dependency forever (probably a bad idea), then add it to `ignoreDeps`. If you want to ignore a major update to a dependency indefinitely, then you can just close the "Update webpack to v4" PR and you won't see it again. You'll still get a PR later on if a version 3.8.2 comes out.

Taking your examples, using default behaviour:

- "1.0.0": This is a pinned version so propose updates whenever there is a newer version available
- "^1.0.0": If 2.0.0 or later comes out, propose a PR for that (e.g. "^2.0.0")
"~1.0.0": If 1.1.0 or later comes out, propose a PR for that (e.g. "~1.1.0")

If your repo is an app, pin everything and get a PR whenever there's a new version. If your repo is a library, then pin devDependencies and set dependencies to be as wide of a range as you wish to support.

The approach you have in mind makes sense if you are manually updating dependencies, but not once you have automation available.

Also consider enabling "lock file maintenance" e.g. weekly, so that you can have your lock file refreshed periodically.

**Comment by chrisforrette** [comment]
@rarkins This is great, thanks for the explanation, it clarifies a lot.

Regarding that last line—enabling lock file maintenance—is that a config option? By the way, I tried to peruse through the docs and look for something like it but it looks like the docs site is on the fritz: https://renovatebot.com/docs

**Comment by rarkins** [comment]
@chrisforrette 	what are you seeing for the docs page? It loads perfectly for me in 3 different browsers and including when I connect via a VPN.

*However* just tonight I was getting broken docs on every PR that Netlify builds.

**Comment by chrisforrette** [comment]
@rarkins I'm seeing an unstyled version of it:
  
![screen shot 2018-12-10 at 12 03 00 pm](https://user-images.githubusercontent.com/126919/49758376-9ec5c580-fc73-11e8-8c3c-ddd0923a8c07.png)

And 404s for some static assets:

![screen shot 2018-12-10 at 12 03 04 pm](https://user-images.githubusercontent.com/126919/49758397-a9805a80-fc73-11e8-8245-bcbd97f7dde2.png)

I tried shift + refreshing and it didn't change.

**Comment by rarkins** [comment]
@chrisforrette does it work if you add a trailing slash? i.e. https://renovatebot.com/docs/ ?
