### ISSUE TITLE
Release notes in commit message body

### ISSUE THREAD

**Issue by mikebryant** [renovatebot/config-help#135]
### Context

Internally we currently have a custom built dependency update tool - basically what renovate does, but it's worse in nearly every way. We started it several years ago, before we knew about renovate. 

One of the main ways we're using it is for multi level dependency updates. 
- Change is committed in A (say a python package)
- This gets pulled into repository B (A docker image)
- This gets pulled into repository C (Kubernetes manifests)

One of the key features we have is that the original semantic commit messages from repository A are pulled into the commit message in repository B. (With a prefix of `fix: `, say, so that message then propagates into repository C). This means that when we're doing the final merge (from an automated PR in the final repo), to deploy to production say, we can see what the original changes were and why we're deploying them.

### Question

How can we achieve the same behaviour in renovate? I'd like to configure the commit message body so it includes the relevant potion of changelog between the two versions.

**Comment by rarkins** [comment]
Do they really need to be in the commit message body of the PR instead of the PR body? On GitHub they’re different things and the latter is much easier. 

One simple way to solve it is if the changelog for package B (the Dockerfile) points to Package A’s repo release notes? That way the PR to package C - for updating Docker image B - will include the original
Python release notes from Package A, and you haven’t lost context. 

As an example, I have a manual override for the Docker Hub “node” image release notes to point to github.com/nodejs/node instead of the repo that builds the Docker image. That way when updating (eg a Kubernetes manifest) then you see regular Node.js release notes.

**Comment by mikebryant** [comment]
The challenge is making sure they're picked up by the next level.

For release notes / changelog I'm currently thinking of using the `semantic-release` tool, which creates the release notes from commit messages - it doesn't look at the PRs that got a commit merged, just the commit itself. (And I think renovate then looks at the release notes?)

It's an interesting idea, but making it so the changelog for B points at A doesn't help in the general case - most of our repositories have more than one dependency. It's arranged as a directed acyclic graph, lots of small subcomponents worked on by different groups come together to form larger artifacts, and so on up the tree. Might be doable in a few cases though.. (But then you lose any important changes from the middle level repo). Thanks for the idea there.

Some of our chains are 5 or 6 levels deep, having the standard of `the commit messages for a repository include all the interesting information for that repo` is easy to reason about with arbitrary nesting. Even if the indentation does get a bit much at higher levels..

**Comment by rarkins** [comment]
I do recommend semantic-release as a way to automate commit messages -> release notes. 

Trying to maintain commit messages and context for 5-6 levels sounds pretty hard though, you may have to settle for being able to easily trace them back rather than view them all in one go. 

If you can think of any extension to Renovate templating though which would help then I’m open to suggestions

**Comment by mikebryant** [comment]
I couldn't see a way to get the release notes in the commitBody template. If it was available as a context variable that could be used that would be enough for our use-case. I think at the moment it's generated later, so it's not available?

And then maybe a preset would be nice-to-have (to document how to use it and so on), though we'd probably end up configuring our own internal preset.

**Comment by mikebryant** [comment]
Actually, another thing that might be required is a way to indent. (e.g. in the commitBody template being able to say `{{releaseNotes | indent(4)}}` type stuff.)

**Comment by mikebryant** [comment]
Mhm, that's fair, I'm sure we could figure something out with the right loops and indentation, stuff like that.

If the template context included both the release notes and urls to the release notes, that would provide a lot of scope for individual users to customise things to their liking.

I'm definitely not suggesting that this happen by default - we're currently willing to accept quite long commit messages, but I wouldn't expect everyone to adopt this approach.

I don't think having it available in the template context by default would affect anyone though?

**Comment by rarkins** [comment]
Right. Adding this extra/earlier metadata could be done without impacting others because by default the commit and PR templates remain the same. 

Each branch/commit/PR (there is a 1:1:1 ratio) contains 1 or more “updates”. Each update can contain 1 or more releases. So you’d need to loop through each update per commit and then loop through each release per update, essentially just like the default prBody does today.

**Comment by rarkins** [comment]
I will track this request as part of https://github.com/renovatebot/renovate/issues/2987 so closing this one as not currently possible to solve with config
