### ISSUE TITLE
Custom config for multiple package.json in different directories

### ISSUE THREAD

**Issue by gmahe** [renovatebot/config-help#136]
I have a project with an architecture with 2 directories, both having their own package.json. I'm using renovate.json on the root dir and self hosted.

What I'm trying to do is having different config for each package.json when I run the renovate cli.
So far i've tried to have different labels on each sub dir, but it doesn't consider the config.
I must be doing it wrong obviously, is there a way of doing it?
```
{
  "repositories": [
    {
      "packageRules": [
        {
          "paths": ["dir1/package.json"],
          "labels": ["dir1", "Renovate"]
        }
      ]
    },
    {
      "packageRules": [
        {
          "paths": ["dir2/package.json"],
          "labels": ["dir2", "Renovate"]
        }
      ]
    }
  ]
}

```

**Comment by gmahe** [comment]
Hey @rarkins I'm using a self-hosted (CLI + renovate.json)
Yes it's in the renovate.json.

**Comment by rarkins** [comment]
`repositories` is not a valid field in `renovate.json`, so try again similar to how you had it:

```
{
    {
      "packageRules": [
        {
          "paths": ["dir1/package.json"],
          "labels": ["dir1", "Renovate"]
        }
      ]
    },
    {
      "packageRules": [
        {
          "paths": ["dir2/package.json"],
          "labels": ["dir2", "Renovate"]
        }
      ]
    }
}
```

**Comment by gmahe** [comment]
This doesn't seem to be a correct json

**Comment by rarkins** [comment]
Edited, should be fixed.

**Comment by gmahe** [comment]
Great it does the job! 
But I'm having a weird behaviour; in the case I'm having the same package in both dir1 and dir2 package.json, the renovate PR will include both dir1 and dir2 Update/Upgrade but will only take the labels of the 2nd one.
Is the logic correct?

**Comment by rarkins** [comment]
Default behaviour is that if a dependency exists in multiple package files then its upgrade will be combined into a single PR. If you don't want that, there are ways to ensure that PRs aren't combined.

Otherwise, it's a little bit random about whether Renovate will take the labels from dir1 or dir2. Essentially it's contradictory configuration so it just picks whichever is first in the array of upgrades when it processes it.

In theory we could make a feature addition to combine/merge all the labels from within the same PR, if that's what you were expecting?

**Comment by rarkins** [comment]
> How can you do that?

Define a custom `branchPrefix` for each path, e.g. `"renovate/dir1-"` instead of default `"renovate/"`.

The suggestion for labels unfortunately won't work because config always "cascades" so the child value overwrite the parent one. In this case the value in the packageRule is most specific to it would take precedence and overwrite any previously defined label.

**Comment by gmahe** [comment]
Ah I see! I didn't think about that!
Thanks.
