### ISSUE TITLE
What repos are used?

### ISSUE THREAD

**Issue by estahn** [renovatebot/config-help#142]
I just upgraded to `Organization Medium` but our org has >200 repositories. Which repositories are being scanned? Is it chosen randomly?

**Comment by rarkins** [comment]
When limiting of repositories is done, it's done alphabetically, and only done once the number of *onboarded* (i.e. you merged the Configure Renovate PR) repos exceeds the allowance. Please email billing@renovatebot.com if you need a custom plan beyond the 100 repos supported by the `Organization Large` plan on GitHub Marketplace.

**Comment by estahn** [comment]
@rarkins I've seen you provide a self-hosted solution. Do you have a helm chart or something similar to set it up on Kubernetes? Or is it just as simple as running a docker container on a scheduled basis?

**Comment by rarkins** [comment]
There's an example Helm chart for self-hosted the open source version here: https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#kubernetes

This should work, but it won't be *responsive*/real-time like the app is, because it's essentially just a CLI tool running on a schedule.

The [Pro version](https://renovatebot.com/pro) adds responsiveness via webhook handling and job prioritisation although doesn't yet have a Helm chart prepared - the example is Docker Compose.

**Comment by estahn** [comment]
Alright, unfortunately, I don't have time to create the helm chart atm otherwise I would go straight to it.  We're currently ok with the hosted version and I will revisit once we reach adoption rates >25 repos.
