### ISSUE TITLE
package.json is not receiving updates / onboarding PR was only for .net projects

### ISSUE THREAD

**Issue by NullVoxPopuli** [renovatebot/config-help#144]
here is my repo: https://github.com/sillsdev/appbuilder-portal/ (open source!)

and the renovate config:

```
{
  "labels": [
    "dependency upgrade"
  ],
  "extends": [
    "config:base"
  ],
  "automerge": false,
  "enabled": true,
  "ignorePaths": [
    "source/OptimaJet.DWKit.StarterApplication/package.json"
  ],
  "packageRules": [
    {
      "packagePatterns": ["(.+)\\.csproj"],
      "ignoreDeps": [
        "Microsoft.EntityFrameworkCore.InMemory",
        "Microsoft.EntityFrameworkCore.Design",
        "Microsoft.EntityFrameworkCore",
        "Microsoft.AspNetCore.StaticFiles",
        "Microsoft.AspNetCore.Mvc",
        "Microsoft.AspNetCore.Http.Abstractions",
        "Microsoft.AspNetCore.Authentication.Cookies",
        "Microsoft.AspNetCore",
        "Microsoft.ApplicationInsights.AspNetCore",
        "BundlerMinifier.Core"
      ]
    },
    {
        "paths": ["source/SIL.AppBuilder.Portal.Frontend/package.json"],
        "rangeStrategy": "replace",
        "enabled": true
    },
    {
        "packagePatterns": ["Dockerfile"],
        "enabled": false
    }
  ]
}
```

we have a package json at `source/SIL.AppBuilder.Portal.Frontend/package.json`

but have haven't received any PRs for any of the deps here.
Is something misconfigured?

**Comment by rarkins** [comment]
This rule doesn't make sense because you are putting a file name pattern into a package name pattern field:

```
    {
      "packagePatterns": ["(.+)\\.csproj"],
      "ignoreDeps": [
        "Microsoft.EntityFrameworkCore.InMemory",
        "Microsoft.EntityFrameworkCore.Design",
        "Microsoft.EntityFrameworkCore",
        "Microsoft.AspNetCore.StaticFiles",
        "Microsoft.AspNetCore.Mvc",
        "Microsoft.AspNetCore.Http.Abstractions",
        "Microsoft.AspNetCore.Authentication.Cookies",
        "Microsoft.AspNetCore",
        "Microsoft.ApplicationInsights.AspNetCore",
        "BundlerMinifier.Core"
      ]
    },
```

What were you hoping to achieve? Ignore them only for NuGet? The naming is pretty unique so you can probably put them at the top level `ignoreDeps`. I doubt this is making an impact though.

Can you log into https://renovatebot.com/dashboard and have a look at the logs first? It may give you some hint as to what's going on or what's going wrong.

**Comment by rarkins** [comment]
This change I proposed should fix the Nuget rule:
![image](https://user-images.githubusercontent.com/6311784/51482997-33096900-1d98-11e9-8a10-a6adc241377a.png)

As for the repo logs, it's because the last job ran on January 17 and the dashboard only shows last 3 days of logs. Somehow the repo got stuck, and I think I've permanently fixed it, but please let me know if you don't see it running ~hourly from now on.

Right now you're still rate limited by 2 PRs per hour, so it's possible the npm ones are still on their way. If you accept the `masterIssue` config PR too the you'll get visibility into that.

**Comment by NullVoxPopuli** [comment]
yes! those config options look like good ideas :)
