### ISSUE TITLE
[Question] How to configure Renovate to update usual dependencies?

### ISSUE THREAD

**Issue by artemirq** [renovatebot/config-help#155]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?

I see, what Renovate updating `devDependencies`, but doesn't updating usual `dependencies`
How to configure Renovate to update `dependencies`?
Thanks

**Comment by rarkins** [comment]
Renovate does update dependencies by default. Can you provide an example of a package.json with dependencies that aren’t being updated? Please include your config too

**Comment by artemirq** [comment]
@rarkins I use Renovate at [Zero Scripts](https://github.com/zero-scripts/zero-scripts) project
Example:
[package.json](https://github.com/zero-scripts/zero-scripts/blob/master/packages/extension.webpack-eslint/package.json#L30)
In this case, I had to [manually update](https://github.com/zero-scripts/zero-scripts/commit/cfb3d553e6027307bb0ca0b152776b770e104b93#diff-7d8408136ac720e39402ffa3894f583dR30). No PRs by Renovate to update this dependency

**Comment by rarkins** [comment]
The reason you're not getting a PR is because v1.1.1 fell within the range `^1.1.0` so there was no upgrade *necessary*. Usually the only reason to use ranges in `package.json` is because you have downstream dependencies that prefer you to keep the range as wide as possible. If you want to keep bumping dependencies to the latest, there's little reason to use ranges - you should probably just be pinning exact versions.

So to get updates in future, you can do either of these:

1. Configure `"rangeStrategy": "pin"`. Renovate will pin any remaining ranges in `dependencies` and then update them each time there's a new version, OR

2. Configure `"rangeStrategy": "bump"`. Renovate will keep ranges but keep bumping them to the latest version, like you did manually in this case from `^1.1.0` to `^1.1.1`.

**Comment by artemirq** [comment]
@rarkins Thanks so much for help. I was stupid :c
