### ISSUE TITLE
[Question] Group node version upgrades

### ISSUE THREAD

**Issue by sjparkinson** [renovatebot/config-help#165]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://renovatebot.com/dashboard#github/financial-times-sandbox/testing-123/45465720

### What is your question?

We have a pull request at https://github.com/Financial-Times/renovate-config-next/pull/27.

My intent is to update our configuration so that pull requests that update Node.js are grouped into a single pull request.

We're testing out this configuration at https://github.com/financial-times-sandbox/testing-123. As you can see from the pull requests, we're almost there, but I can't seem to group the CircleCI upgrade with the `.nvmrc` and `package.json` upgrades.

The crux of the change is at https://github.com/Financial-Times/renovate-config-next/pull/27/files#diff-76e62915fba4048ac877a875e2e3b8d2R80.

Any ideas?

**Comment by rarkins** [comment]
We actually aim to provide this for everyone already, so we should be able to achieve this. 

To get all updates into the same PR means you need to get them into the same *branch*. Right now I see `renovate/node-8.x` and `renovate-node`.

By the way, why do you also have `node` listed in `ignoreDeps`?

**Comment by rarkins** [comment]
The default Renovate config should group circleci/node with your nvmrc and package.json engines. Here's an example: https://github.com/renovate-tests/node3/pull/1

The lambda image isn't ready/compatible with Renovate yet, so there's no PR to update. Their tag is like `lambci/lambda:build-nodejs6.10`. Ideally it should be like `lambci/lambda:6.10-build-nodejs` in order to be detected as a valid version.

So for now I'm not sure if there's anything to actually do here. Maybe you need to *remove* some config if the default groupings got broken by your package rules?

**Comment by sjparkinson** [comment]
> By the way, why do you also have node listed in ignoreDeps?

Ah, forgot about that! We didn't what to use Renovate to manage upgrading node initially. But now we're up for it!

I will think about the branch issue.

We changed the default to `renovate-` so we didn't have to worry about the git folder name thing, if anyone every made a branch called `renovate`. I'll try undoing that.

**Comment by rarkins** [comment]
It should also work fine with `renovate-` branch prefix. I tested it to verify: https://github.com/renovate-tests/node3/pull/2

**Comment by sjparkinson** [comment]
Thanks, deleting the node package rules and removing the ignore seems to have done the trick.

https://github.com/financial-times-sandbox/testing-123/pull/21 🚀
