### ISSUE TITLE
[Question] “Action required: Add a Renovate config” on seemingly valid configured repo

### ISSUE THREAD

**Issue by ticky** [renovatebot/config-help#183]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Yes, I haven’t been able to find any indication of what caused this issue to be opened (the dashboard UI is nigh unusable on Mobile!). Closest I can find is this log with authentication errors in it: 
https://renovatebot.com/dashboard#github/ticky/fisher-yates-map/51726045

### What is your question?
Is my config actually invalid as ticky/fisher-yates-map#11 suggests, or did Renovate get itself confused for some reason? I have a config file:

https://github.com/ticky/fisher-yates-map/blob/develop/renovate.json

**Comment by rarkins** [comment]
Thanks for raising this. I've debugged a little and found:

- A temporary GitHub error returned bad credentials when we were retrieving the file list. In such cases we should probably just throw/exit but instead we proceeded as if there were no files, and the issue was created

- Right now we don't autoclose that issue if resolved. I was trying to avoid doing it as it will cause an extra 1-2 API calls per run for for the 99.5% of repos with a config.. but it seems like we need to. Once implemented, you will see this issue closed. Please keep it open if you don't mind, as it will be a good way for me to verify the fix.

**Comment by rarkins** [comment]
confirmed fixed, thanks!
