### ISSUE TITLE
How to configure renovate to run go mod tidy

### ISSUE THREAD

**Issue by matoous** [renovatebot/config-help#188]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### Have you checked the logs? Don't forget to include them if relevant
I have checked the logs. Can include them if needed.

### What is your question?
I want to run renovate on our golang repository on GitLab. We deployed it on our servers. It created all the PRs nicely but I'm not able to configure 2 things:

1. gomod tidy, I want the renovate bot to run `go mod tidy` before submitting the PR but it doesn't do that. I cloned to repo to test it, whenever I run `renovate --endpoint="https://[gitlabendpoint].com/api/v4/" --platform=gitlab --log-level=debug --git-fs=https testing/repo` it should show either log of running `go mod tidy` or at least warn me that it is not possible with given gitFs, but I see neither.

2. when I do the process described above, e.g. running the command on cloned testing repo, renovate creates 28 MR's even with the limits, how is it so?

Here's my config. I can provide anything else if needed but I would love to make everything work.

My config:
```
{
    "commitMessagePrefix": "dependency:",
    "commitMessageTopic": "Update dependency {{depName}}",
    "labels": ["importance/low", "difficulty/low", "process/needs-review", "type/feature", "dependency"],
    "vulnerabilityAlerts": {
        "labels": ["security"]
    },
    "pipenv": {
        "enabled": true
    },
    "prConcurrentLimit": 5,
    "prHourlyLimit": 3,
    "postUpdateOptions": ["gomodTidy"],
    "gomod": {
        "enabled": true
    }
}
```

**Comment by rarkins** [comment]
There are a few topics to cover here. I'll go top to bottom in your config to start with.

Instead of setting `commitMessagePrefix`, I recommend using `"semanticCommitType": "dependency"`.

Do not set `commitMessageTopic` unless you really have to, and do not include "Update" in it. It's better if you describe which message you didn't like and I can tell you the simplest way to change it. Generally we try to use the best description for each manager, e.g. "dependency" for npm, "crate" for Rust, "module" for Go, "image" for Docker, etc.

`vulnerabilityAlerts` are only supported for GitHub currently, as they expose their DB. You may as well remove this for GitLab.

prConcurrentLimit and prHourlyLimit should be taking effect. You would need to run at debug and look in the logs for information on these limits. New logs won't help now (unless Renovate is creating any new MRs) - you need the logs from when the MRs were created. So therefore I recommend saving logs of every run in case you need to reference them earlier.

`goModTidy` requires `gitFs`, which I'm guessing you're aware of. But gitFs=https doesn't work properly for GitLab, so you need to use gitFs=ssh instead. You can read this doc about kubernetes as it also includes a description of getting ssh to work for GitLab: https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#kubernetes-for-gitlab-using-git-over-ssh

You can see that Renovate should either run goModTidy or warn, according to the source code: https://github.com/renovatebot/renovate/blob/75608e9f6db7f055be53233ba2c3d4c06794c575/lib/manager/gomod/artifacts.js#L81-L105

Once you have gitFs=ssh working, you should rebase one of the MRs with go modules to get it to try again.

**Comment by matoous** [comment]
Hi! Thanks for help, now everything is running smoothly. We just had to set it up to run with `gitFs=ssh`. One more think please, I set `"prConcurrentLimit": 5` but the bot created 10 PR's for go modules, does it apply the limits after one type of dependency check? Or why didn't it obeyed the limits?

**Comment by rarkins** [comment]
@matoous the PR limit should be applied regardless of the package manager. It's possible that there's a bug for the check or perhaps for GitLab or gitFs specifically. If you have the logs from when the extra PRs were created, please raise an issue in the main repo so that it can be checked out.
