### ISSUE TITLE
Is there a timeline for Bitbucket server support?

### ISSUE THREAD

**Issue by donotello** [renovatebot/config-help#199]
[Bitbucket server support](https://github.com/renovatebot/renovate/tree/master/lib/platform/bitbucket-server) is in "alpha" as of now.

I'm wondering if there is a timeline to move it to beta, RC and remove the label completely? This is important because unfortunately in our company we can't use alpha releases in production environment. I can do a trick and say that the renovate bot itself is not in the alpha but now sure if it will work :)

We use Bitbucket v6.1.3 and plan to host renovate bot in Openshift cluster.

Another question I have is what kind of whitelistening is required for renovatebot. Is there a documentation on this? This will help me with configuration in openshift which doesn't usually have access to Internet.

**Comment by rarkins** [comment]
It’s been heavily tested recently and will be considered GA within the next week

**Comment by donotello** [comment]
@rarkins great news!

Was it tested with both 5.x and 6.x?

And sorry for adding two questions in one issue but what kind of whitelistening is required for renovatebot. Is there a documentation on this? This will help me with configuration in openshift which doesn't have access to Internet.

**Comment by rarkins** [comment]
Bitbucket Server support is now considered "GA" and docs updated accordingly.

Renovate itself doesn't require any internet access of its own (e.g. phone home to Renovate servers, etc). However if you need it to fetch from public registries (npmjs, pypi, packagist, Docker Hub, etc) then you need to whitelist all of those servers. If any more questions, please raise it in a separate issue so that it's not lost/confused by others.
