### ISSUE TITLE
[Question] groupName: all still submits multiple PRs

### ISSUE THREAD

**Issue by tonyxiao** [renovatebot/config-help#201]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
I'm trying to get renovate to send a single PR for all dependency updates by following the FAQ here https://renovatebot.com/docs/faq/
![image](https://user-images.githubusercontent.com/696842/55551858-9cf39800-5690-11e9-9dc7-6136c8dfb5da.png)

And this is our `renovate.json`

![image](https://user-images.githubusercontent.com/696842/55552017-11c6d200-5691-11e9-912c-d02f6644e605.png)

However, in our react-native app w/ yarn monorepo renovate tells us that it's going to send 3 separate PRs for updates, which is very confusing

![image](https://user-images.githubusercontent.com/696842/55552076-3458eb00-5691-11e9-8748-189f7abba3ef.png)

I thought groupName `all` would result in only one PR?

**Comment by rarkins** [comment]
I can fix this - the documentation is a little out of date. Are you sure you want to combine all upgrades including major though? I’m many cases it will mean your PRs fail tests due to one or more breaking major updates.

**Comment by tonyxiao** [comment]
@rarkins I don't have enough experience with renovate at the moment to know how it feels when it gets going so I'm just going by the workflow we're currently using. (which is me manually going to `yarn upgrade-interactive --latest`, upgrade all, fix what's broken, then merge)

**Comment by tonyxiao** [comment]
I'm sure as we use renovate more we'd fine tune it to work in a more idiomatic way

**Comment by tonyxiao** [comment]
Also, is there a way for me to add comments into renovate.json? (for example I'd love to put this issue URL in it) - i.e. does renovate support configuring via json5 or js?

**Comment by rarkins** [comment]
Solution: remove `"groupName": "all"` and instead add `"group:all"` to your `extends` array. You can see the source for it if you're interested here: https://renovatebot.com/docs/presets-group/#groupall

Right now there's not a way to add comments but it's a good idea. JSON5 would be preferred because if it's JS then we need to take the extra time to execute it in a sandbox "just in case". Could you [raise a feature request](https://github.com/renovatebot/renovate/issues/new?template=4-Feature_request.md) with a quick example of your config converted to JSON5 and including comments?

**Comment by tonyxiao** [comment]
Done, thank you! and confirmed working
