### ISSUE TITLE
PR for full latest version, not just major

### ISSUE THREAD

**Issue by mcjfunk** [renovatebot/config-help#205]
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
Yep, not relevant here

### What is your question?
We are using `^` ranges in our package.json and we have `"rangeStrategy": "replace"`. Our intent is to only get Renovate PRs when a major version bump takes place to a dependency.

But, lets say a certain dependency publishes a major version, 2.0.0, followed by a patch fix in close succession. When we get that PR, we'd love for the version change that is made to the package.json to include the fully qualified "latest" version of that repo, in this example ^2.0.1. Similarly, when we onboard new repos, a dependency may be at 3.4.2, but the PR will only be for ^3.0.0.

I realize that npm install will still pull down the latest, but it would give me a warm fuzzy feeling if it used the full latest version in the PR.

Is there any way to achieve this? The rangeStrategy of "bump" would result in PRs for every minor and patch, which is not what we are after. Thanks!

**Comment by rarkins** [comment]
To help me understand, why are you using ranges instead of exact versions?
- Because it's a library?
- It's an app, but because ranges mean less PRs for you?

> npm install will still pull down the latest

Only if there's no lock file present

**Comment by mcjfunk** [comment]
Library. We have about 130 node libraries my team maintains. After contemplating and trying various different range strategies and "pinning" scenarios, we chose to go with ranges. We do not use package-lock files for our libs, only apps.

**Comment by rarkins** [comment]
Thanks for the further info. Right now, there are two approaches to ranges you're probably aware of:

1. "replace" <-- Keep ranges as wide as possible, because that's typically what libraries should do. i.e. only bump the minimum version if it's for a compatibility problem or because it's too hard to maintain.
2. "bump" <-- Keep ranges up to date with the latest. This is not really how you're meant to use ranges, but quite a few users swear by it!

In your case, it sounds like you want this?
- "replace" for current version, i.e. don't change it
- "bump" to the very latest when adopting a new major

Are you sure bumping to the very latest next major is best for your downstream consumers? It essentially restricts them - temporarily - to just a single version possible.

Another challenge is working out how any new rule for this would behave when ranges are non-caret. e.g. `~1.2.0`. Would you want `~1.3.0` or `~1.3.1`?

If you *only* use caret ranges, then you could configure a packageRule/rangeStrategy combination like this:

```json
  "rangeStrategy": "bump",
  "packageRules": [{
    "updateTypes": ["minor"],
    "enabled": false
  }]
```

Example repo: https://github.com/renovate-tests/majorbump1

As you can probably guess - it works by setting rangeStrategy to "bump" for all packages, but then disabling minor updates. The result is major bumps, but it only works if you're sure all the packages it affects have a caret range. It doesn't work to set rangeStrategy based on updateTypes because the updateType is determined at the same time rangeStrategy is used.

**Comment by mcjfunk** [comment]
Thanks for the quick response! That's interesting. I'll have to weigh the pros and cons here. One more question, would you also need to disable the patch versions with that approach? 

```
  "rangeStrategy": "bump",
  "packageRules": [{
    "updateTypes": ["minor", "patch"],
    "enabled": false
  }]
```

**Comment by rarkins** [comment]
Unless you have explicitly enabled patch/minor separation, you shouldn’t see any

**Comment by rarkins** [comment]
You can definitely add patch to the list like you suggest though - nothing to lose
