### ISSUE TITLE
[Question] Is it possible to configure renovate via a .github config/

### ISSUE THREAD

**Issue by gauntface** [renovatebot/config-help#218]
### Which Renovate are you using? CLI, App, or Pro
Renovate forking app

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
N/A

### What is your question?
I love renovate but having to keep on maintaining a config file in each repo is troublesome. I'd love it if there was a way to configure renovate for all my repos. Is there a solution for this?

**Comment by rarkins** [comment]
The current approach is this:

1. Create a Renovate [config preset](https://renovatebot.com/docs/config-presets/) e.g. a `renovate.json` in https://github.com/gauntface/renovate-config
2. Set your config in each repository to be `{ "extends": ["github>gauntface/renovate-config"] }`

The above means that the shared config will be used by all the other repositories and if you make changes then you need to make changes just in one location.

Additionally, you can request me to add a server-side rule to the bot so that every *new* repository onboarded in your domain automatically gets this preset suggested in the "Configure Renovate" PR rather than `"config:base"` as happens today.

I understand there's a movement towards defining a special repo per-org that tools like Renovate can read a shared config from. I'm open to this idea too although would like to see it proposed/discussed as a feature request to make sure it's done right, as I haven't explored it myself.
