### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Hongarc** [renovatebot/config-help#223]
- Which Renovate are you using? CLI

- Which platform are you using? local

- Have you checked the logs? Don't forget to include them if relevant

How to test config before push it to git?

I want to see the result when I apply that config.

Thanks

**Comment by rarkins** [comment]
The best time to test your config is when you do onboarding, because it provides you a preview then. But assuming you are past that point, there are some options you can try:

1. Fork your repository and then the new config against the fork. Include `--include-forks=true` in your CLI command on the forked repository, otherwise Renovate will skip it.

2. Another approach is to commit your config but then run Renovate with `--dry-run=true`. It won't do anything and will just print what it would do to the logs.

3. Another approach is to enable `"masterIssueApproval": true` in your config. That way Renovate never creates PRs without you approving them in the master issue, although it may still autoclose some. More details: https://renovatebot.com/blog/master-issue

**Comment by Hongarc** [comment]
That is my repo so I can't fork, but I can create a new branch to change and check, but I don't want to create any pull request, I want everything in local.

It isn't able, is it?

**Comment by rarkins** [comment]
Instead of fork, you can Import a repository as a new one (non-fork) using this menu in GitHub: 
![image](https://user-images.githubusercontent.com/6311784/56847758-8206f300-68df-11e9-9283-5017a37430d0.png)

Otherwise no, there is not really a way to do this.

**Comment by Hongarc** [comment]
I want only in local, but this is a good option, I hope to renovate can support run repo local

**Comment by rarkins** [comment]
What do you mean "local"? A local clone of a repo? Renovate supports github, gitlab, bitbucket and azure devops. It needs their APIs and can't run against pure git.

**Comment by Hongarc** [comment]
My mean is run a project on my computer (clone from git)

**Comment by rarkins** [comment]
This could be challenging to implement, but I think it's a good idea to be able to do that type of dry run locally. I created this feature request in the main repo: https://github.com/renovatebot/renovate/issues/3609
