### ISSUE TITLE
[Question] More frequent pull requests

### ISSUE THREAD

**Issue by mkarp** [renovatebot/config-help#253]
### Which Renovate are you using? CLI, App, or Pro

App.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub.

### Have you checked the logs? Don't forget to include them if relevant

Yeap.

### What is your question?

Hey there! We already love Renovate Bot. I wonder if I'm missing some configuration option to make it merge the pull requests instantly after the checks pass.

It seems like that the bot operates on an hourly (or perhaps 30 min) schedule. It opens a pull request, the checks pass within 10 minutes, and then the pull request stays open for another 30-45 minutes until Renovate merges it.

Here's how our dashboard looks like, you can see the hourly cadence. The bot still goes through the initial batch of pull requests, we have around 40 of them queued.

<img width="445" alt="Screenshot 2019-05-28 at 15 07 56" src="https://user-images.githubusercontent.com/318902/58480538-d7daef00-815a-11e9-807f-fe2130dd009c.png">

Here's the config:

```
{
  "branchPrefix": "renovate/",
  "enabledManagers": [
    "deps-edn",
    "leiningen"
  ],
  "prHourlyLimit": 0,
  "prConcurrentLimit": 2,
  "labels": [
    "dependencies"
  ],
  "automerge": true,
  "major": {
    "automerge": false
  },
  "rangeStrategy": "pin",
  "separateMultipleMajor": true,
  "schedule": ["after 9am and before 6pm on every weekday"],
  "timezone": "Europe/Berlin",
  "rebaseStalePrs": true
}
```

What I would like for Renovate Bot to do is to merge the pull requests as soon as all of the checks pass. Is there an option to do that?

Thanks!

**Comment by rarkins** [comment]
It ideally should be done this way, but currently it is not.

When GitHub sends webhooks about status checks (tests), it only tells us the status of one check, and not if the branch/PR is actually all green. Therefore if we ran every time anything passed a test, we'd run too often and use up the repo's API limit for the hour. We know the type of logic required to overcome this, but it hasn't been written yet.

Because you're getting set up and have a large backlog, I will add a manual cron job every 10 minutes for you so at least the delay won't be so long. Of course that won't be perfect, but it will be better.

**Comment by mkarp** [comment]
Thanks @rarkins for getting back so quickly!

**Comment by rarkins** [comment]
I'll close this config-help issue for now because there's nothing that can be done by config, but will try to remember to find it and comment here so you know when the functionality you've asked for has been implemented.
