### ISSUE TITLE
[Question] Deleted version still visible in PRs

### ISSUE THREAD

**Issue by Scritik** [renovatebot/config-help#267]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
Hi,

It seems that react-images created a version (0.6.7) and deleted it after (https://www.npmjs.com/package/react-images). Renovate continues to create a PR about it. Do you have some kind of cache on your side?

Thanks.

**Comment by rarkins** [comment]
Are you sure that 0.6.7 was deleted?

**Comment by Scritik** [comment]
Ok, I just noticed that the version is still on NPM but at the end of the list (4 years ago).

![Capture d’écran, le 2019-06-11 à 11 28 23](https://user-images.githubusercontent.com/216583/59285687-5eec9480-8c3c-11e9-9c8a-1227c3d9c09e.png)

I can't see any release/tag about this version (and the bump is really weird) so I guess they deleted it some way. https://github.com/jossmac/react-images/releases
So the issue is more on NPM side but do you have a way to detect it?

**Comment by rarkins** [comment]
Npm’s registry is the source of truth for npm packages, not GitHub. If it’s on npm then it exists. The authors should deprecate that version on npm if they don’t want anybody using it. Why is it a problem in your case? You can close any PR and the version will be ignored.

**Comment by Scritik** [comment]
Ok, so the issue is really on react-images side.

I can't really ignore it because I grouped all the minor/patch updates together. But I'm just gonna update the major version to fix the issue. I was not sure at the beginning from where the issue was. Thanks!

**Comment by rarkins** [comment]
Looking at their releases (http://registry.npmjs.org/react-images) it definitely looks abnormal. The simply and most obvious thing the authors should do is deprecate 0.6.7 on npmjs, which I've suggested in their repo. You could also do this in Renovate by using a packageRule:

```
{
  "packageRules": [{
    "datasources": ["npm"],
    "packageNames": ["react-images"],
    "allowedVersions": "!= 0.6.7"
  }]
}
```

BTW I am guessing that the following happened:
- Version 0.5.9 was tagged as "latest" on npmjs. Therefore Renovate correctly ignored 0.6.7 because it's greater than `latest`
- Version 1.0.0 was released and tagged as `latest`
- Now, both 0.6.7 and 1.0.0 are valid upgrades according to npm

**Comment by Scritik** [comment]
Well, I don't like the idea to create a rule for this since I can upgrade to 1.0.0.
The version is still not deprecated and the the road to the 1.0.0 was really badly handled so I think I'm going to investigate other options.

Thanks for the help!
