### ISSUE TITLE
[Question] Error when rolling pro container to latest version

### ISSUE THREAD

**Issue by QuentinMoss** [renovatebot/config-help#314]
### Which Renovate are you using? CLI, App, or Pro
pro self hosted

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

github
### Have you checked the logs? Don't forget to include them if relevant

```
textPayload: "         "stack": "error: syntax error at or near \";\"\n    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:602:11)\n    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:399:19)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:121:22)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)"
```

Here's a diff between deployments: 
```
[quentinmoss@localtoast-v2.local]$ git diff origin/master
diff --git a/kubernetes.yaml b/kubernetes.yaml
index 9883804..72fa4c7 100644
--- a/kubernetes.yaml
+++ b/kubernetes.yaml
@@ -29,7 +29,7 @@ spec:
           cloud.google.com/gke-nodepool: ...
       containers:
         - name: renovate-pro
-          image: renovate/pro:0.16.2
+          image: renovate/pro:0.16.0-pre.2
           imagePullPolicy: Always
           ports:
             - name: http
```

### What is your question?
Thoughts?

**Comment by rarkins** [comment]
Isn’t that a downgrade? Or is the the diff misleading?

**Comment by QuentinMoss** [comment]
diff is misleading, I had to revert to fix the error. Sorry about that.

Crashing happened on  renovate/pro:0.16.2

**Comment by rarkins** [comment]
I've just tested 0.16.2 on a fresh laptop against github.com and no error. We also have at least a few customers running 0.16.2 already against GHE that I'm aware of.

Because the Pro database contains essentially ephemeral data, are you able to try 0.16.2 "directly"? i.e. brand new DB, and not migrating from 0.16.x? FYI though the other customers did migrate from lower versions, and we always intend that you should be able to migrate. Also.. there's no SQL differences within 0.16.x either.

Finally, the *full* bootup log would help if the error still persists. This might give an indication as to what SQL is somehow triggering the parse error in the pg client library we use.
