### ISSUE TITLE
What do you mean "Combine any patch and minor upgrades together into same branch/PR"?

### ISSUE THREAD

**Issue by ryo-utsunomiya** [renovatebot/config-help#36]
Renovate onboarding PR says: "Combine any patch and minor upgrades together into same branch/PR"
https://github.com/ryo-utsunomiya/amazon-block/pull/1

I expected Renovate would combine any patch/minor updates into 1 PR.
However, Renovate splitted each updates.
https://github.com/ryo-utsunomiya/amazon-block/pulls
(For example, https://github.com/ryo-utsunomiya/amazon-block/pull/10 and https://github.com/ryo-utsunomiya/amazon-block/pull/12 are both minor/patch updates, but were separated into two PRs )

Can I make Renovate combine patch/minor updates into 1 PR?

**Comment by rarkins** [comment]
This setting is referring to patch/minor upgrades of the *same dependency*. e.g. if you are using dep-a@1.0.0 and versions 1.0.1 and 1.1.0 are released, this setting means that you get only one PR (for v1.1.0) and not two for v1.0.1 and v1.1.0 separately.

FYI I have since changed the description of that preset to say, "Do not separate patch and minor upgrades into separate PRs for the same dependency"

If you want a single PR that combines minor upgrades of all dependencies then you can try this config:

```
 "minor": {
    "groupName": "all dependencies",
  }
```

**Comment by ryo-utsunomiya** [comment]
Thanks! I understood the meaning, and your configuration worked perfectly.
https://github.com/ryo-utsunomiya/amazon-block/pull/16
