### ISSUE TITLE
[Question] BumpStrategy vs Lock File Maintenance

### ISSUE THREAD

**Issue by dslemay** [renovatebot/config-help#362]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
N/A

### What is your question?
I am wondering what the difference is between the bump rangeStrategy and maintaining lockfiles for the configuration. I have my configuration set up [here](https://github.com/dslemay/Portfolio-Site/blob/master/renovate.json) and have been merging pull requests with the bumped version. I noticed that the lock file was being updated in those pull requests. I was surprised to see there more updates to the lock file in the [lock file maintenance PR](https://github.com/dslemay/Portfolio-Site/pull/359).

What additional maintenance is the lock file maintenance doing that is not already in the other PRs? I'm trying to both understand the difference and determine if it is a recommended approach to have both enabled.

**Comment by rarkins** [comment]
A lot of this answer is specific to the package manager behaviour and not Renovate itself. 

When you do a "bump", you're essentially saying to npm/yarn something like "Here is my current config and lock file. Please update package X to v1.2.3". They will update X to v1.2.3 and try to keep as much else unchanged as possible. e.g. even if an upgrade to Y is available too, it will keep Y fixed at what version it was on, unless it's impossible. So essentially bump means "the minimum changes to the lock file to update X to v1.2.3". This behaviour is package manager-specific.

When Renovate does lock file maintenance, it deletes the lock file before running npm/yarn. So therefore you will get the absolute latest of every package, both direct and indirect.

I recommend you do lock file maintenance weekly, because any more often and you might find it too noisy (packages update *all the time*). For bump, if you're running an app then you should consider if pinning your direct dependencies makes more sense and gives better visibility.

**Comment by dslemay** [comment]
@rarkins Thank you so much. This is really helpful.
