### ISSUE TITLE
[Question] Renovate doesn't seem to update all dependencies

### ISSUE THREAD

**Issue by deiga** [renovatebot/config-help#366]
### Which Renovate are you using? 
App

### Which platform are you using? 
GitHub

### Have you checked the logs? Don't forget to include them if relevant

https://app.renovatebot.com/dashboard#github/deiga/Jon-Van-Til/98362267

### What is your question?

So, I have this repo, which I started off with using dependabot and then migrated to renovate. I still haven't been able to remove dependabot, because renovate has not tried to upgrade all dependencies.

Here is the repo https://github.com/deiga/Jon-Van-Til

It currently has 4 dependabot PR's about updates, but renovate has not tried to upgrade those dependencies.

It's especially worrisome as some of those are security-related updates.

Can you explain why this is happening?

**Comment by rarkins** [comment]
You need to configure [rangStrategy](https://docs.renovatebot.com/configuration-options/#rangestrategy) to be "bump" if you want your ranges to be bumped instead of left as-is. You really need to ask why you're using ranges at all though instead of pinned versions if you want them bumped to the latest version anyway?

One of the four PRs you have is for a nested dependency security update, which we don't support right now. I suggest you enable vulnerability PRs from GitHub (which uses dependabot[bot] not dependabot-preview[bot]) and combine that with Renovate for regular dependency updates.

**Comment by deiga** [comment]
@rarkins Sorry, that I didn't get back to this. I would have expected renovate to at least bump the lockfile so that dependencies were kept up-to-date

**Comment by rarkins** [comment]
@deiga you can do that, but many don't want that so it's not the default. Switch it on with one line config.

You didn't answer though:

> why you're using ranges at all though instead of pinned versions if you want them bumped to the latest version anyway?

For a webapp, I consider it to be bad practice to use ranges in `package.json`. They should only be used for libraries.

**Comment by deiga** [comment]
@rarkins Oh, just because I just used the base config, without too much thought put into it :)

I like the idea that only libraries should use semver ranges

**Comment by rarkins** [comment]
Just to be clear, we support either way! But for range use, we found the majority of users want "less noise" so that's why we don't default to lockfile-only updates. Set `rangeStrategy=bump` and you should get the behaviour you desire.
