### ISSUE TITLE
[Question] How to enable renovate for specific monorepo dependencies

### ISSUE THREAD

**Issue by toxsick** [renovatebot/config-help#375]
### Which Renovate are you using? CLI, App, or Pro
CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### What is your question?

Given the following configuration:

```
{
  "baseBranches": ["develop"],
  "extends": [
    "config:base",
    "default:enableVulnerabilityAlerts",
    "default:ignoreModulesAndTests",
    "default:pinVersions",
    "default:prHourlyLimit2",
    "docker:disable"
  ],
  "packageRules": [
    {
      "packagePatterns": ["*"],
      "enabled": false
    },
    {
      "depTypeList": ["devDependencies"],
      "enabled": true,
      "automerge": true,
      "major": {
        "automerge": false
      },
      "prConcurrentLimit": 10,
      "rebaseStalePrs": true
    },
    {
      "extends": ["default:automergeMinor"],
      "packagePatterns": "^@fortawesome",
      "groupName": "fortawesome dependencies",
      "enabled": true
    },
    {
      "extends": ["monorepo:react", "default:automergeMinor"],
      "groupName": "react monorepo",
      "enabled": true
    },
  ]
}
```

My first packageRule disables all packages by default and the second enables minor automerge for devDependencies. Now I want to enable renovate (with automergeMinor) for specific (production) dependencies again. The @fortawesome (no devDependency) rule works as expected. 

The problem is that the react monorepo rule ONLY creates merge requests for devDependencies included in the monorepo. There are no merge requests created for e.g. react itself. Do I have to add depTypeList to the rule? If yes I don't understand why, because then the fontawesome rule would need that too or not?

THX and regards

**Comment by toxsick** [comment]
@rarkins do you need more information from me?

regards

**Comment by rarkins** [comment]
As a first step, I'd suggest avoiding using `extends` within your `packageRules` and instead put the rules directly in. We can maybe add them back later once we've worked out that they're not causing the problem. Particularly for the react case.

**Comment by toxsick** [comment]
Ok digging a little deeper with debug log level gives me:

```
DEBUG: packageFiles with updates (repository=xx/repo)
       "config": {
         "npm": [
          ...
           {
             "packageFile": "packages/xx/package.json",
             "manager": "npm",
             "deps": [
               ...
               {
                 "depType": "dependencies",
                 "depName": "react",
                 "currentValue": "16.8.6",
                 "datasource": "npm",
                 "prettyDepType": "dependency",
                 "lockedVersion": "16.8.6",
                 "updates": [],
                 "skipReason": "disabled"
               },
               ...
```

So I my first packageRule seems to skip it:

```
    {
      "packagePatterns": ["*"],
      "enabled": false
    },
```

Adding a packageRule like this works and creates a new merge request for react:

```
    {
      "extends": ["default:automergeMinor"],
      "packagePatterns": "^react$",
      "groupName": "react monorepo",
      "enabled": true
    },
```

**Comment by rarkins** [comment]
The way packageRules works is that you have selectors, and then you have actions. Right now we don't do a great job of documenting which is which, and users can sometimes be confused. Selectors means things like `packagePatterns` or `updateTypes`. But for example people can think `"updateTypes": ["minor", "patch"]` means "only do minor and patch" rather than "match against minor and patch".

Anyway, the first rule clearly matches all packages and disables then. It seems the original iteration of rules was not catching all the react packages and re-enabling them, while your later/simpler rule does. In other words, this rule was not somehow matching those react packages packages:

```
{
      "extends": ["monorepo:react", "default:automergeMinor"],
      "groupName": "react monorepo",
      "enabled": true
    },
```

I would need to manually expand out the `extends` above to understand what's going wrong.

**Comment by toxsick** [comment]
Thanks for the clarification.

>I would need to manually expand out the extends above to understand what's going wrong.

That means adding these directly:

- https://github.com/renovatebot/presets/blob/master/packages/renovate-config-monorepo/package.json#L346-L347
- https://github.com/renovatebot/presets/blob/master/packages/renovate-config-default/package.json#L270-L281

Something like this?

```
    {
      "groupName": "react monorepo",
      "sourceUrlPrefixes": [
        "https://github.com/facebook/react"
      ],
      "minor": {
        "automerge": true
      },
      "patch": {
        "automerge": true
      },
      "pin": {
        "automerge": true
      },
      "lockFileMaintenance": {
        "automerge": true
      }
    },
```

So it would help if I try to run it with a rule like this? But I guess only debug output wouldn't help right?

**Comment by rarkins** [comment]
Yeah, so in that case the selector is:
```
      "sourceUrlPrefixes": [
        "https://github.com/facebook/react"
      ],
```

And it seems it isn't actually matching the react packages. Is it just the `react` package that should be caught? Here's its definition on npmjs:

![image](https://user-images.githubusercontent.com/6311784/66702968-a0d23800-ed0d-11e9-86f4-22ab32cef6a2.png)

**Comment by rarkins** [comment]
Reproduced the problem here: https://github.com/renovate-tests/npm10

**Comment by rarkins** [comment]
OK, I figured out why this is happening. Here's the order we do things:

- Extract dependencies
- Apply packageRules
- Look up dependency versions
- Apply packageRules

The problem is that `react` is getting disabled in step 2 above, before we know its sourceUrl from step 3. This is not something easy to change, so I'm going to close this as unfortunately expected behaviour. In conclusion: if you disable all packages using packageRules, you need to re-enable them by name and not by sourceUrl.

**Comment by toxsick** [comment]
@rarkins thanks for clarification, I will try to do it differently then.

regrards
