### ISSUE TITLE
[Question] rangeStrategy is set to update-lockfile but renovate is still pinning

### ISSUE THREAD

**Issue by yjaaidi** [renovatebot/config-help#381]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Github

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Found npm package files
INFO: Processing 12 branches: renovate/angular-monorepo, renovate/codelyzer-5.x, renovate/core-js-3.x, renovate/eslint-6.x, renovate/jest-24.x, renovate/jest-preset-angular-7.x, renovate/pin-dependencies, renovate/rxjs-6.x, renovate/ts-jest-24.x, renovate/ts-node-8.x, renovate/tslint-5.x, renovate/typescript-3.x
INFO: Branch automerged(branch="renovate/pin-dependencies")
```

### What is your question?
As you can see here : https://github.com/jscutlery/http-ext/blob/develop/.github/renovate.json
we are using the following configuration `"rangeStrategy": "update-lockfile"` but we still receive `pin-dependencies` PRs that pin all our dependencies to a strict version.
Is there anything wrong with the configuration?

Thank you in advance.

**Comment by rarkins** [comment]
I'm trying but failing to locate the commits referred to. The log you give mentions "Branch automerged" but then you mention pin-dependencies "PRs", which you probably wouldn't get if the branch was being automerged.

This 5 day old PR was merged into master so presumably came before you updated your config: https://github.com/jscutlery/http-ext/pull/7

If I look back in the history of your config, it seems like this was exactly what you had configured back then: https://github.com/jscutlery/http-ext/blob/513261b67e48aae85acb6150f9e110fe680ce649/.github/renovate.json

Finally - important, Renovate always pulls its config from the **default** branch of a repo, so make sure you're always looking at https://github.com/jscutlery/http-ext/blob/master/.github/renovate.json instead of the one in `develop` branch.

**Comment by yjaaidi** [comment]
Thank you so much @rarkins!
I guess that was exactly the issue, the configuration wasn't up-to-date on our default branch. I thought renovate was checking the config for each branch which in fact wouldn't make sense 😊
Great job by the way

**Comment by rarkins** [comment]
OK, I'll close this for now, please reopen or create a new issue if any future questions
