### ISSUE TITLE
[Question] Forking Renovate - Permission denied when pushing to renovate branch

### ISSUE THREAD

**Issue by Feiyang1** [renovatebot/config-help#382]
### Which Renovate are you using? CLI, App, or Pro
Forking Renovate App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### What is your question?
Renovate PR failed CI, so we need to make a fix in code and push it to the PR. When pushing to the renovate branch, my teammate is getting permission denied error:
```
remote: Permission to renovate-bot/firebase-js-sdk.git denied to USERNAME.
fatal: unable to access 'https://github.com/renovate-bot/firebase-js-sdk.git/': The requested URL returned error: 403
```

It's weird that I can push without problem. There is probably a place that grants user permission, but I can't remember where and how?

**Comment by rarkins** [comment]
These types of permissions are actually controlled at a lower level by GitHub/git and not configurable via Renovate. Looking at your example, I see that it's a fork off a repository you own:
![image](https://user-images.githubusercontent.com/6311784/66799961-8cf82300-ef13-11e9-945b-b7c13d591870.png)

So that probably explains why GitHub grants you permissions to push to it. I can't think of any perfect solutions for a teammate. They could add Renovate's repository as a remote to their own fork and pull the branch from there, later submitting their own PR that replace's Renovate's. Or potentially you could edit the PR to change its target branch so that it's merged into a temporary branch that you have granted rights to your teammate for.

**Comment by Feiyang1** [comment]
Thanks! That makes sense.
I added my teammates as collaborators to my fork to experiment, but it didn't work either. I will ask the team to use the workaround you provided. Thanks again.
