### ISSUE TITLE
Renovate force pushes unnecessary commits

### ISSUE THREAD

**Issue by simoneb** [renovatebot/config-help#390]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes, but they're not particularly enlightening. This is the job when the unnecessary force push occurred: #105519224

### What is your question?

Since a while ago I started noticing that Renovate sometimes force pushes commits to its own branches even when those commits are unnecessary. In the specific case above, Renovate is updating files `package.json` and `package-lock.json`.

Unfortunately I can't share the PR as it's a private repository, but what I observed is:

- Renovate opened the PR a couple of days ago to update `testdouble` from `3.10.0` to `3.12.4`. The PR isn't merged yet
- When opening the PR it created a commit with short SHA `95d38acd`
- A few minutes ago it forced pushed to that same branch a commit with short SHA `3f0480b` which contains exactly the same changes as the original commit. I double checked this by going through the diff and confirming that all changes to the two involved files are identical.

I don't have a problem with Renovate doing this in principle, except that it seems unnecessary and also it triggers unnecessary email notifications which are sent by GitHub when you're watching a repository.

Is there a reason why Renovate would force push identical commits?

**Comment by rarkins** [comment]
If you search for "rebas" in the debug logs you should see some info about Renovate's decision making on when to rebase. If it says "Branch is stale and needs rebasing" then that's usually because either (a) you enabled rebasing of stale branches in Renovate's config, or (b) you have branch protection enabled for master that says all PRs must be kept up to date. In the case of (b), Renovate will keep its branches/PRs up to date with master unless you set `"rebaseStalePrs": false` in config.

**Comment by simoneb** [comment]
@rarkins thanks, great explanation. Indeed the master branch had changed and we have the requirement to keep PR branches up to date with master before merging, so the reason seems to have been (b)
