### ISSUE TITLE
How to create a schedule

### ISSUE THREAD

**Issue by chrisl8** [renovatebot/config-help#399]
### Which Renovate are you using? CLI, App, or Pro
Github

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
Github

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What is your question?
I cannot make a schedule work.
What I *want* is for it to run on Friday mornings before 8am.

I have tried in `renovate.json` so far is:
1.
```
{
  "extends": [
    "config:base",
    "schedule:earlyFridays"
  ]
}
```
Apparently "earlyMondays" is a thing, but "earlyFridays" is not. I do not understand why.

2.
```
{
  "schedule": "before 8am on Fridays",
  "extends": [
    "config:base"
  ]
}
```
I copied this from https://docs.renovatebot.com/presets-schedule/ but it apparently does not work.

3.
```
{
  "extends": [
    "config:base"
  ],
  "schedule": [
    "before 8am on Friday"
  ]
}
```
Some information suggest that the schedule should be in an array? However, this just resulted in it running any time anyway.

No matter what I do, it either does not work or it breaks the config.

Can you provide a simple example to run on Fridays before 8am?

Thank you.

**Comment by rarkins** [comment]
> Apparently "earlyMondays" is a thing, but "earlyFridays" is not. I do not understand why.

If a preset isn't already predefined, then it doesn't exist. I see you already discovered the list of schedule presets though so now know which you can use.

> Some information suggest that the schedule should be in an array?

Here is where the definition of `schedule` says that it's also ok to use a string instead of array: https://github.com/renovatebot/renovate/blob/f157c1ef816a86efbbaa2fcb8909dc4aeb1d69ac/lib/config/definitions.ts#L85

> "schedule": "before 8am on Fridays",

It's incorrect to add the "s" to Friday. The example you copied from said `on Monday` so you should say `on Friday`.

This is what you wrote in your last config, but please double check what exactly you have in your config.

Also, if you log into app.renovatebot.com/dashboard and search debug messages for "schedule" then it might give you a hint as to what's going wrong, if it's not the "Fridays" thing.

**Comment by chrisl8** [comment]
Thank you. I put the last entry back as you suggested:
https://github.com/chrisl8/witchazzan-client/blob/master/renovate.json

and the log has no errors, so I hope it worked:
https://app.renovatebot.com/dashboard#github/chrisl8/witchazzan-client/107643597
(That link may be private to me? I'm not sure)

I'm not entirely sure how to know if it worked, but at least it didn't display any errors. In some cases old pull requests showed changes in the schedule, but they just show "Schedule: At any time (no schedule defined)." so maybe they just kind of update their text randomly.

**Comment by rarkins** [comment]
I note that the most recent PR has this confirming its schedule:

![image](https://user-images.githubusercontent.com/6311784/67742101-5514d380-fa1b-11e9-8ff0-6ac1031376a3.png)

**Comment by chrisl8** [comment]
Except that the config file says:

```
{
  "extends": [
    "config:base"
  ],
  "schedule": [
    "before 8am on Friday"
  ]
}
```
https://github.com/chrisl8/witchazzan-client/blob/master/renovate.json

Why does the PR say "before 3am on Monday" (UTC). if I set the config to "before 8am on Friday"?

**Comment by rarkins** [comment]
Because that's what you had it configured it to when the PR was created: https://github.com/chrisl8/witchazzan-client/commit/8edc2d2a9573968054fe2c280dfb6fea2c400b6a#diff-76e62915fba4048ac877a875e2e3b8d2
