### ISSUE TITLE
[Question] Encrypted Docker Credentials?

### ISSUE THREAD

**Issue by ekristen** [renovatebot/config-help#401]
### Which Renovate are you using? CLI, App, or Pro

CLI

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitLab

### What is your question?

Is there anyway to configure docker credentials encrypted like an encrypted npm token? I don't want to commit plaintext credentials in the hosts definition into every project to be able to do dockerfile renovation for private docker registry images?

**Comment by rarkins** [comment]
If you're running your own bot then you can put the credentials into your bot's `config.js`, removing the need to configure them per-project.

**Comment by ekristen** [comment]
I tried but doesn’t seem to work?

**Comment by rarkins** [comment]
`hostRules` defines in `config.js` should work.

**Comment by ekristen** [comment]
Interesting. I’ll try again. Logs redact the auth information, is there a flag to prevent that so I can troubleshoot?

**Comment by rarkins** [comment]
No, there is no flag to disable that. But debit level may still tell you enough

**Comment by rarkins** [comment]
I tested against docker.io and using github as host and confirmed that Docker credentials in hostRules is working in that scenario. e.g.

```js
  hostRules: [{
    hostType: 'docker',
    domainName: 'docker.io',
    username: 'rarkins',
    password: 'abc123'
  }]
```

With the above configuration, Renovate was able to find updated tags for a private docker image on Docker Hub. Using `domainName` instead of `hostName` can be important for some because the auth server might not have the URL you expect.

Unfortunately there was no debug message that helped confirm for sure that credentials were applied. I ran Renovate on debug mode to confirm that.

**Comment by ekristen** [comment]
It looks like I’ve got it working. I was missing hostType And had a very subtle typo that I wasn’t immediately seeing. I’m waiting for my team to have an updated docker image to validate its working.

**Comment by rarkins** [comment]
It should work without `hostType` actually. But I like to be specific just to be safe.

**Comment by ekristen** [comment]
It was probably the typo. Still waiting on a newer image in the org to test. I’ll close for now. Thank you so much.
