### ISSUE TITLE
[Question] Renovate won't make PRs for minor or patch updates

### ISSUE THREAD

**Issue by adambowles** [renovatebot/config-help#421]
### Which Renovate are you using? CLI, App, or Pro
CLI @ 19.66.8

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### What is your question?
Currently using the default config (`extends: ['config:base']`)

How do I configure Renovate to create PRs for all updates to a dependency, currently it is creating only major updates:  
![image](https://user-images.githubusercontent.com/10128574/68686352-6acde100-0563-11ea-88ee-3a35e3d4c695.png)
(Latest webpack is 4.41.2)

For other dependencies that are already at the latest major, but minors have been released, Renovate does not create any PR (e.g. husky@3.0.0 when latest is 3.0.9)

**Comment by rarkins** [comment]
It doesn’t update because you are using ranges and the ranges are still satisfied by the newer versions. Use ranges if you need a wide range of versions supported (eg writing a library) but otherwise I recommend pinning of versions so it’s more explicit. It usually makes no sense to use range syntax if you keep bumping the range to allow only the latest version anyway. 

Anyway, config can save you either way here, but first please tell me if you wish to continue ranges or not.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adambowles** [comment]
Perfect, thanks!

Changing from ranges (e.g. `"husky": "^3.0.1"`) to exact versions (e.g. `"husky": "3.0.1"`) does exactly what I wanted!

![image](https://user-images.githubusercontent.com/10128574/68749509-40793380-05f6-11ea-9e4b-d4bab81bc217.png)
