### ISSUE TITLE
Override pr limits by package?

### ISSUE THREAD

**Issue by Flydiverny** [renovatebot/config-help#428]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
Can I ignore `prConcurrentLimit` and `prHourlyLimit` for specific packages?
Ie we have in-house packages that we want to always open new PRs (since its mostly automerge on them) 

Id like to have a config like:
```json
    "automergeInhousePatches": {
      "packageRules": [
        {
          "extends": [
            "@company:inhousePackages",
            ":automergePatch"
          ],
          "prPriority": 5,
          "prConcurrentLimit": 0,
          "prHourlyLimit": 0
        }
      ]
    },
```

**Comment by rarkins** [comment]
I’ll need to dig through the code to be sure if that concept could be supported, but it sounds like a good idea 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Flydiverny** [comment]
I'm thinking maybe adding a `ignorePrLimit` or something could suffice, so if a pr includes at least one package which ignores hourly and concurrency limits it will be created regardless. Seems to me like this could be added to the branch processor without changing how the limits are handled other than that. I think it makes sense for other PRs to still be limited by those that bypass the limit. Not sure if it should affect priority? Ie should those that are bypassing be sorted earlier or just be sorted like normal. Would affect the possibility of gaining one or two PRs if eg you have 1 remaining pr to create, and one which has the highest prio and one that bypass, depending on how these are sorted you might get one or two PRs with this solution.

**Comment by rarkins** [comment]
I think that potentially PR priority + varying limits could result in some slightly-hard-to-predict outcomes, but they should still be deterministic all the same. We sort PRs based on PR priority already, but what I need to check is that we evaluate each branch individually against PR limits so that even if the first X branches are blocked due to limits that branch X+1 could be created if its limits are higher.

Let's say that you have a default setting of 10 concurrent PRs and 10 are already created. Let's say that you also have two branches waiting that have a limit set to 11 concurrent PRs. In that case, whichever is sorted first (either due to priority, or update type) will get created that run while the second one will be rate limited. I think this result seems OK to me.
