### ISSUE TITLE
[Question] Docker registry-mirrors support?

### ISSUE THREAD

**Issue by cobexer** [renovatebot/config-help#430]
### Which Renovate are you using?
Pro 0.18.0-pre.4

### Which platform are you using?
GitLab

### What is your question?
Docker supports `registry-mirrors` to pull images from a local cache instead of `docker.io`:
https://docs.docker.com/v17.12/registry/recipes/mirror/#configure-the-docker-daemon

I couldn't find information about this in the configuration documentation, how can this be configured?

Considering that there are quite a few Docker registries around, the best way would be if hostRules could alias docker registries to other URLs like:

mappings:
* `docker.io` to `docker-io.artifactory.example.com`
* `quay.io` to `quay-io.artifactory.example.com`

including of course authentication support.

**Comment by rarkins** [comment]
You should be able to use `registryUrls` to proxy any basic Docker.io images, e.g.

```json
{
  "packageRules": [{
    "datasources": ["docker"],
    "registryUrls": ["docker-io.artifactory.example.com"]
  }]
}
```

This should result in any `x/y` images being looked up from that registry instead of docker.io.

I can't think of any way to *rewrite* the lookup if a hostname is specified though, because `registryUrls` only works if no Registry is already set: https://github.com/renovatebot/renovate/blob/67d82c5f16a6619a62bf12128917e0267d35fb59/lib/datasource/docker/index.ts#L26-L28

Anything beyond that would require a feature request and some thought about how we can keep things backwards-compatible.

BTW Renovate doesn't pull entire images so you don't need the proxy if bandwidth saving is all that matters. The only reason to enforce a local proxy is if you need air gapping.

**Comment by cobexer** [comment]
I guess the documentation of `registryUrls` needs to be updated then

> This is only necessary in case you need to manually configure a registry URL to use for datasource lookups. Applies to PyPI (pip) only for now. Supports only one URL for now but is defined as a list for forward compatibility.

Anyway, the suggested configuration works! Thanks!

**Comment by rarkins** [comment]
Pull Requests for docs always welcome! The docs are in the open source repo
