### ISSUE TITLE
[Question] Docker + Node.js supportPolicy

### ISSUE THREAD

**Issue by emmercm** [renovatebot/config-help#437]
### Which Renovate are you using? CLI, App, or Pro

App, previously pro but now free.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub.

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What is your question?

I have a `Dockerfile` that looks similar to:

```dockerfile
FROM node:10-alpine

# ...
```

and a slim config that looks like:

```json
{
    "extends": [
        "config:base"
    ],

    "docker": {
        "major": {
            "enabled": true
        }
    },

    "node": {
        "supportPolicy": ["lts_latest"]
    },
}
```

and the onboarding PR tells me it's going to `Update Node.js to v13` (`13-alpine`), but v13 doesn't follow `"supportPolicy": ["lts_latest"]`.

Removing the wrapping `"node":{}` doesn't change anything.

Is this combo currently supported? Or is there an elegant way I can restrict the update to even (LTS) versions?

**Comment by rarkins** [comment]
`supportPolicy` is an option/concept that we never fully matured. Turned out to be harder to implement than we expected. Discussion here: https://github.com/renovatebot/renovate/issues/2443

Anyway, we deliberately disable Node major updates by default but I'm guessing that your docker.major.enabled = true config is counter-overriding that and re-enabling them.

Until the above issue is properly resolved (feedback welcome there) then I'd recommend:
- Disabling major node updates for Renovate
- Bumping major releases yourself but using Renovate to bump minor/patch

Although, keeping as-is isn't too problematic - if you have a "Upgrade Node.js to v13" PR and close it then it won't come back again. i.e. it's hopefully just once per year that you need to close one.

**Comment by emmercm** [comment]
I tried to do my due diligence searching for related issues but didn't find that one, thank you for linking it.

I think the following will more or less do what I want:

```json
// Update Node outside of Docker base images
"node": {
    "major": {
        "enabled": true
    },
    "separateMultipleMajor": true
},

// Update Node Docker base images
"docker": {
    "major": {
        "enabled": true
    },
    "separateMultipleMajor": true
}
```

but it will end up creating v11, v12, and v13 branches/PRs. Is there a way to use `allowedVersions` in combination with Node? The name `packageRules` is throwing me off, I've used it with npm but not with an entire language version update.

**Comment by rarkins** [comment]
Yes, you should also be able to use `allowedVersions`

**Comment by emmercm** [comment]
What I've ended up with is something like:

```json
{
    "extends": [
        "config:base"
    ],
    "packageRules": [
        {
            "packageNames": ["node"],
            "major": {
                "enabled": true
            },
            "separateMultipleMajor": true,
            "allowedVersions": "^8 || ^10 || ^12"
        }
    ]
}
```

and that should work for me, it groups and handles dockerfile + nvm.

This can probably be closed out.

**Comment by rarkins** [comment]
Thanks. If you ever find that things you need to do could potentially be greatly simplified with better syntax, don't hesitate to suggest it within the main repo. Also, contributions to our published presets are also welcome if you think something you configure would be helpful to others.
