### ISSUE TITLE
[Question] "pin dependencies" PR created while ":preserveSemverRanges"

### ISSUE THREAD

**Issue by mightyiam** [renovatebot/config-help#441]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

GitHub app

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### Have you checked the logs? Don't forget to include them if relevant

Yes. Not sure what's going on there.
https://app.renovatebot.com/dashboard#github/mightyiam/shields-badge-data/115350508

### What is your question?

I thought that ranges were going to be preserved because I [configured it that way](https://github.com/mightyiam/shields-badge-data/blob/f2ea83cf32024b54f4c6c197ef741b24f50c3928/renovate.json#L4). But I am getting the ["pin dependencies" PR](https://github.com/mightyiam/shields-badge-data/pull/135).

Help?

**Comment by mightyiam** [comment]
Here's another one, same problem:
https://github.com/cycle-components/component-template/pull/98

Am I doing something wrong?

**Comment by rarkins** [comment]
I think the `config:js-lib` preset might be configuring `devDependencies` to pin and dependencies to not, and the `preserveSemverRanges` preset is not strong enough to override the `devDependencies` setting in the base config. 

FWIW, you should pin `devDependencies` regardless of using Renovate or not.

**Comment by rarkins** [comment]
Try with `config:base` present and then add `”rangeStrategy”: “replace”` to your config if you really want to keep ranges in `devDependencies`

**Comment by mightyiam** [comment]
Thank you for the tip, @rarkins . Could you please explain this "strong enough" term, please?

**Comment by rarkins** [comment]
`config:js-lib` includes this preset: https://github.com/renovatebot/presets/blob/9579a0894309a045461a1f001dda0c36b2b36e12/packages/renovate-config-default/package.json#L94-L116

You can see it includes a rule to pin `devDependencies`.

It's more specific than this one: https://github.com/renovatebot/presets/blob/9579a0894309a045461a1f001dda0c36b2b36e12/packages/renovate-config-default/package.json#L50-L53

Package Rules get evaluated after regular config, so that's why it's taking precedence.

So if you look at your config today, it's basically `config:base` plus a preset you don't agree with, then with another preset to try to override the first one. Hence why it would be better just to use `config:base` plus `:preserveSemverRanges`

**Comment by mightyiam** [comment]
Thank you for the explanation, @rarkins . The way this is currently documented doesn't seem to go into the subject of specificity, unless I missed that part.

**Comment by rarkins** [comment]
We are hoping to remove most of the confusion/ambiguity in the next major release with a tweak of the logic to remove the impact of specificity
