### ISSUE TITLE
`bumpVersion` set to `patch` does not upgrade correctly

### ISSUE THREAD

**Issue by wywfalcon** [renovatebot/config-help#444]
**What Renovate type are you using?**

I am using the Docker image but this does not matter.

**Describe the bug**

When upgrading an Alpine version in the Dockerfile which was previously set to `v3.9` and `bumpVersion` set to `patch`, it should upgrade to `v3.10.3` instead of `v3.10`.

**Did you see anything helpful in debug logs?**

There is no error in this scenario.

**To Reproduce**

Set a Docker image with `FROM alpine:3.9`, run Renovate and see that it upgrades to `3.10`

**Additional context**

That's it. It hopefully is not a big change on your end.

**Comment by rarkins** [comment]
That's not what `bumpVersion` is intended for. It's a Node.js-only feature and is used to bump *your* `package.json` version whenever your dependencies are updated. We may extend it to other languages but it still won't ever be related to upgrading dependencies themselves like you thought.

For Docker, Renovate keeps the same precision as you already have, e.g. `3.9` -> `3.10`. If you want it to keep update at a "patch" level, you'll need to change your Dockerfile to a patch version to begin with.

One day we might support what you wish for as part of `pin` functionality, but because Docker does not enforce "true" Semver then the logic to achieve this would be a little difficult.
