### ISSUE TITLE
[Question] Why cannot set postUpdateOptions through ENV variable?

### ISSUE THREAD

**Issue by rpadovani** [renovatebot/config-help#451]
### Which Renovate are you using? e.g. CLI, GitHub app, GitLab app, etc.

Docker

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

Gitlab

### What is your question?

I am using a serverless solution to run renovate, so I specify all the config through env variables. 
I see, however, that `postUpdateOptions` is not allowed as env variable: https://github.com/renovatebot/renovate/blob/8f1abcc389c6b4b18dece86414d3cae51027073e/lib/config/definitions.ts#L1401

Why so?
There is something I can do to enable it? (Including a patch to the source code, if necessary)

Thanks for the amazing tool :-)

**Comment by rarkins** [comment]
We try to keep the list of env variables limited so that `renovate --help` doesn't spit out too many pages of options. Usually I'd recommend this type of config option should live either in your `renovate.json` or perhaps in a preset config that you share amongst all repositories.

I'm not against enabling this option in env if you really need it, but you should probably also think about hosting your own centralised "preset" regardless as it can be much easier to manager as well as more transparent.

**Comment by rpadovani** [comment]
Gotcha, I should indeed use shared presets. Thanks for the explanation :-)
