### ISSUE TITLE
Unable to access private registry

### ISSUE THREAD

**Issue by zebbedi** [renovatebot/config-help#480]
### Which Renovate are you using?

- [ ] Renovate Open Source CLI
- [x] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using?

- [x] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

I'm trying to set up the renovate github app. I've managed to get it working with basic config however we use our own private Nexus instance which requires authentication even on fetch requests. It basically just proxies on to npmjs main registry and ALL packages are fetched through it. 

When our CI build runs we dynamically write out a .npmrc file with the following:

```
registry=https://nexus.xxxxxxxxx.com/repository/npm-group/
always-auth=true
_auth=xxxxxxxxxxx
```

So in renovate I've added the following config:

```json
{
  "extends": [
    "config:base"
  ],
  "encrypted": {
    "npmToken": "xxxxxxxxxxx"
  },
  "npmrc": "registry=https://nexus.xxxxxxxxx.com/repository/npm-group/\nalways-auth=true\n_auth=${NPM_TOKEN}",
  "labels": [
    "renovate"
  ],
  "prCreation": "not-pending",
  "rangeStrategy": "replace",
  "statusCheckVerify": true,
  "ignoreDeps": [
    "eslint-plugin-react-hooks"
  ]
}
```

The problem however is that it seems unable to fetch the config:base. Our corporate firewall blocks all access to the private Nexus instance unless it originates from our network so i'm guessing it could be that. We do have various rules setup however to allow other things running in AWS access, but can anyone advise what I need to get security to allow for the renovate bot to have access? Is there a specific IP range or something?

The error we receive from renovatebot in the logs is:

```
DEBUG: Found npmrc in decrypted config - setting
DEBUG: Setting npmrc
DEBUG: Preset fetch error
{
  "err": {
    "message": "dep not found",
    "stack": "Error: dep not found\n    at Object.getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/datasource/npm/presets.js:8:15)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (config:base)"
  }
}
DEBUG: raiseConfigWarningIssue()
```

If i remove the nprmc property from the renovate config then it all works fine except obviously it then can't access our private packages.

**Comment by rarkins** [comment]
Hi,

First a friendly tip re: GitHub issues and markdown. If instead of this:
![image](https://user-images.githubusercontent.com/6311784/71163112-b9e6f000-224c-11ea-9f43-6a41b0fc1042.png)

You do this:
![image](https://user-images.githubusercontent.com/6311784/71163186-dbe07280-224c-11ea-980b-70416e3daed7.png)

Then it looks a lot better. I edited your body above for you already.

**Comment by rarkins** [comment]
Renovate runs in the AWS Oregon region but does not have any fixed IP address range that you could whitelist.

If your Nexus instance blocks from unknown IP addresses then it sounds like you'll never be able to update any internal packages because lookups will always fail.

If you leave settings as-is (i.e. using npmjs.org) then it could partly work. Renovate could update public packages successfully but you will probably see the resolved URLs in your lock files changing from your private registry host to the public ones.

You might want to consider WhiteSource Renovate On-Prem? (previously known as Renovate Pro). It allows you to self-host a stateful Renovate server including webhook support and you'd be able to host it on a static IP that you can set a whitelist for.

**Comment by zebbedi** [comment]
Thanks for fixing the formatting, I was indeed struggling. 

We did indeed notice that the urls changed as we were going to just ignore the private packages, but decided to try to get it working when we same the changes. 

Ok, that's helpful thanks. I'll speak to security and see what they want to do. I believe another colleague has requested a trial of on premise as that may be the better approach.
