### ISSUE TITLE
Maven: unable to update prerelease versions

### ISSUE THREAD

**Issue by chingor13** [renovatebot/config-help#490]
**What Renovate type are you using?**

Forking renovate GitHub app

**Describe the bug**

Renovate does not seem to be able to find "prerelease" versions of Maven dependencies. Maven versioning allows for things like `0.1.2-alpha`.

**Did you see anything helpful in debug logs?**

```
       "config": {
         "maven": [
           {
             "datasource": "maven",
             "packageFile": "pom.xml",
             "deps": [
               {
                 "datasource": "maven",
                 "depName": "com.google.cloud:google-cloud-asset-bom",
                 "currentValue": "0.115.0-beta",
                 "fileReplacePosition": 1025,
                 "registryUrls": ["https://repo.maven.apache.org/maven2"],
                 "updates": [],
                 "warnings": [],
                 "sourceUrl": null
               }
             ]
           }
         ]
       }
```

It cannot seem to find version 0.116.0-beta which you can find https://search.maven.org/artifact/com.google.cloud/google-cloud-asset-bom or https://repo.maven.apache.org/maven2/com/google/cloud/google-cloud-asset-bom/maven-metadata.xml

**To Reproduce**

I created a test repo: https://github.com/chingor13/renovate-test

**Additional context**

If it matters, this is in a `<dependencyManagement>` section of the `pom.xml`.

**Comment by rarkins** [comment]
By default, Renovate only updates *to* an unstable version if either:
1. You set `ignoreUnstable` to false
2. It's the same major.minor.patch

e.g. we'd update from `0.115.0-beta.1` to `0.115.0-beta.2` by default but not from `0.115.0-beta` to `0.116.0-beta`.

If you think this use case is common for Maven and Renovate should be able to automatically determine this special case, please raise a feature request in the main repo with some examples/documentation, otherwise we'll close this out as a config issue here.

**Comment by chingor13** [comment]
Thanks! We had seen updates attempted for guava (28.1-android to 28.1-jre) which now makes sense given rule 2.
