### ISSUE TITLE
Is it possible to configure the PR title to include the previous version number? E.g., "Bump eslint-plugin-react from 7.12.3 to 7.17.0"

### ISSUE THREAD

**Issue by tcg** [renovatebot/config-help#493]
### Which Renovate are you using? x the right box:

- [x] Renovate Open Source CLI
- [ ] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ ] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [x] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant
n/a

### What would you like to do?

**Is it possible to configure the PR title to include the previous version number?** For example, Dependabot PR titles look something like this: 

`Bump eslint-plugin-react from 7.12.3 to 7.17.0`

Having that "previous version" available in the "from X to Y" format is very helpful to seeing at a glance if something is a Major/Breaking version bump, without having to look at a dependencies file (`package.json`, etc). 

After looking over the [configuration options](https://docs.renovatebot.com/configuration-options/), and customization available for `commitMessage`, it's not clear to me how, if it's even possible.

**Comment by rarkins** [comment]
Hi @tcg - sorry I missed this one last week and am a little slow in replying.

> Having that "previous version" available in the "from X to Y" format is very helpful to seeing at a glance if something is a Major/Breaking version bump

First of all, Renovate's defaults attempt to alleviate this because:
- For non-major updates, Renovate uses the full version (e.g. `Update eslint-plugin-react to v7.17.0`)
- For major updates, Renovate shortens to the major version, (e.g. `Update eslint-plugin-react to v8`)

Use Renovate for more than a week or two and you should get pretty used to this and be able to distinguish immediately.

If you wish to adapt the PR title, first know that is is inherited from the `commitMessage` (generally, they are the same). Within the `commitMessage`, it's [commitMessageExtra](https://github.com/renovatebot/renovate/blob/409c1c5f7fa0a430e09bcaa4d7de74d6449efc3a/lib/config/definitions.ts#L1212-L1220) that defines the "to X" part.

I did a little test here to confirm: https://github.com/renovate-tests/npm3/blob/master/renovate.json

You can see the resulting PRs here: https://github.com/renovate-tests/npm3/pulls

Note: by default Renovate's template has a nice feature where it prefixes versions with `v` (e.g. `v2.0.0` instead of `2.0.0`) but I removed that according to your example given.
