### ISSUE TITLE
Simple weekly non-major npm updates

### ISSUE THREAD

**Issue by shaunwarman** [renovatebot/config-help#508]
### Which Renovate are you using? x the right box:

- [X] Renovate Open Source CLI

### Which platform are you using? x the right box:

- [X] GitHub.com

### What would you like to do?
I'd like to schedule one weekly (Monday) morning dependency update for all non-major npm versions of my project. And I'd like to keep just 1 active PR at a time.

Would the below handle this?

```json
{
  "extends": [
    "config:base",
    "group:allNonMajor",
    "schedule:weekly"
  ]
}
```

**Comment by rarkins** [comment]
The above will result in a single PR for all non-major updates, but that also means that **major** updates will be separated into their own PRs, which means more than 1 active PR. If you set `prConcurrentLimit=1` then you may find that confusing because you may have a backlog of major PRs you're not aware of. As an alternative, I suggest:

```json
{
  "extends": [
    "config:base",
    "group:allNonMajor",
    "schedule:weekly"
  ],
  "masterIssue": true,
  "major": {
    "masterIssueApproval": true
  }
}
```

The above will mean you get a "master issue" to track updates and major update PRs can then be created on-demand. This is in use in the Renovate repository itself too.

**Comment by shaunwarman** [comment]
Thanks @rarkins - this looks great! Will give it a try.
