### ISSUE TITLE
Why are merged pull requests commited by both renovate and renovate-bot users?

### ISSUE THREAD

**Issue by rfgamaral** [renovatebot/config-help#511]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

As an example, let's use https://github.com/rfgamaral/eslint-config-typescript-unified/pull/78 pull request.

I'm using the "Squash and merge" option to merge my dependencies to `master` and this is what I get when I press that button on GitHub:

![image](https://user-images.githubusercontent.com/96476/73435449-9087ac80-4340-11ea-9a1e-ebf2d0c23b0f.png)

So far so good, but here's what I get in the commit history after clicking "Confirm squash and merge":

![image](https://user-images.githubusercontent.com/96476/73435538-c0cf4b00-4340-11ea-8fa3-5f3038e680cc.png)

I mean, why was this commited by both `renovate` and `renovate-bot`? Is this the expected behavior? 

If it's expected and nothing will be changed on your side and since that Renovate adds the `Co-authored-by` to every pull request, maybe it would make sense for the commit author to be the user who pressed the "Confirm squash and merge"? Is there anyway to tweak this behavior?

**Comment by rarkins** [comment]
This is done so that Renovate can submit *signed* commits. Apps can’t sign via git because GitHub doesn’t assign them a real email address. 

Can you rebase merge instead, Renovate will always have only one commit per branch/PR

**Comment by rfgamaral** [comment]
> This is done so that Renovate can submit _signed_ commits. Apps can’t sign via git because GitHub doesn’t assign them a real email address.

So if I remove the "Co-authored-by" comment, the commit won't be signed?

> 
> Can you rebase merge instead, Renovate will always have only one commit per branch/PR

Never used that and just tried it with a new PR, that committed with my username and was authored by Renovate. It's a solution, but that won't sign the commit by Renovate.

**Comment by rfgamaral** [comment]
> Can you rebase merge instead, Renovate will always have only one commit per branch/PR

Just realized that doing this also removed the issue number from the commit message so I'd rather "squash and merge" and avoid changing anything manually.

**Comment by rarkins** [comment]
Neither squashing or rebase merging will preserve the signed commit - this is a limitation of GitHub itself (note: it’s not a true git rebase, despite the terminology).

There’s no problem at all to remove the co-authored-by text when squash merging. It’s a recent feature by GitHub that appears to be aimed towards people getting appropriate credit in PRs.

**Comment by rfgamaral** [comment]
> Neither squashing or rebase merging will preserve the signed commit - this is a limitation of GitHub itself (note: it’s not a true git rebase, despite the terminology).
> 
> There’s no problem at all to remove the co-authored-by text when squash merging. It’s a recent feature by GitHub that appears to be aimed towards people getting appropriate credit in PRs.

But I just tried this with a new PR (removing the "Co-authored-by" text) and used "squash and merge":

![image](https://user-images.githubusercontent.com/96476/73441282-a39f7a00-434a-11ea-8555-cabe01bc9228.png)

And this is what I observe in my commit history:

![image](https://user-images.githubusercontent.com/96476/73441337-c29e0c00-434a-11ea-952a-e7c3b549ca2d.png)

The commit is authored and signed by Renovate bot. This seems to be exactly what I was looking for, the only downside is that I have to edit the commit body with every PR (this can't be customized, can it?). Or am I missing something?

**Comment by rarkins** [comment]
Based on your screenshot, my past comment about signing seems to be based on outdated experience. It looks like GitHub may be signing your squash commit *itself* somehow, so that they can display it as "Verified" as you'd expect. Previously people found it unintuitive that you'd merge a signed commit and it would be unsigned, so maybe they wanted to address that, but it's new to me. It's not technically the same as the commit being signed by Renovate itself but effectively just as good from a user perspective. I'd be interested to see the low-level git log of it.

I think the following is a correct updated summary:
- A GitHub app cannot sign commits via git because it has no real email address assigned
- A bot/app can push commits that are signed by a "real" user account (in this case @renovate-bot)
- If you merge squash a PR that is created by one account (including by an app) but the commit is by a second account, then GitHub will insert a Co-authored-by line no matter what

By the way, it's possible for the Renovate app to be reconfigured to *not* sign commits for you and instead commit from the same "app user" account as the pull request. But in this case it won't be signed/Verified.

**Comment by rfgamaral** [comment]
I guess the only thing that "bothers" me is this:

![image](https://user-images.githubusercontent.com/96476/73435538-c0cf4b00-4340-11ea-8fa3-5f3038e680cc.png)

I can "workaround" it by removing the "Co-authored-by" comment from every "squash and merge. Without I get this:

![image](https://user-images.githubusercontent.com/96476/73532066-bfbb1e00-4413-11ea-9ca6-bf65532b89d6.png)

It's commited by Renovate (and only shows 1 bot) and it's also signed. Good. But to do this I have to remove the "Co-authored-by" from every PR manually, which is cumbersome.

Another ting that bothers me a bit is that all those commits are linked to `renovate[bot]` and when I click that link (i.e., https://github.com/rfgamaral/eslint-config-typescript-unified/commits?author=renovate%5Bbot%5D) I get this:

![image](https://user-images.githubusercontent.com/96476/73532543-cb5b1480-4414-11ea-869e-a71950e39c10.png)
