### ISSUE TITLE
Automerging not working and bot ignoring specific package

### ISSUE THREAD

**Issue by GabrielDuarteM** [renovatebot/config-help#514]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

no logs mentioning `@types/node`. (ctrl+f yielded no results)

about not automerging `@types/chrome`, I have the following, which says that it is not ready for merging (and doesn't say the reason). Checking the PR, you can see that there's no red checks, so it should be ready.

```
DEBUG: Checking #72 for automerge(branch="renovate/chrome-0.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: PR is configured for automerge(branch="renovate/chrome-0.x")
INFO: PR is not ready for merge(branch="renovate/chrome-0.x")
```

### What would you like to do?

The idea is to always automerge `@types/chrome` and `@types/node`, no matter what version it is, to get both packages always up-to-date.

The problems: 
- Renovate stopped creating PRs for `@types/node` after version `v11.13.9` (current version is `13.7.0`)
- `@types/chrome` is never automerged

You can check the repo which I'm having problems here: 
https://github.com/GabrielDuarteM/youtube-autoclose-ads
- `renovate.json` as of today: https://github.com/GabrielDuarteM/youtube-autoclose-ads/blob/a62897bbfb39077f7b24e5c340f4a179b9994cfd/renovate.json
- PR that does not automerge: https://github.com/GabrielDuarteM/youtube-autoclose-ads/pull/72

**Comment by rarkins** [comment]
`@types/node` major upgrades are specifically ignored as part of the `config:base` preset: https://github.com/renovatebot/presets/blob/5504708c878a31a53a2123649355e196086c5d5f/packages/renovate-config-helpers/package.json#L12-L23

This is because we never thought up a good way to enforce the link between node version and `@types/node` version. You can add the opposite package rule to your config if you wish, or upgrade it manually to the next major version and then Renovate will resume minor/patch updates.

**Comment by rarkins** [comment]
The reason automerge wasn't working was because Renovate wasn't actually checking your repository. Because it had no recent commits it was classified as "stale" and is only queued once per week. The previous time it was checked was february 4th, so I ran a manual job just now and it worked.
