### ISSUE TITLE
Run preinstall scripts with yalc

### ISSUE THREAD

**Issue by jamesmillerburgess** [renovatebot/config-help#528]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

[Renovate Log.txt](https://github.com/renovatebot/config-help/files/4196824/Renovate.Log.txt)

### What would you like to do?

We use `yalc` internally to manage local packages, and include `preinstall` scripts in `package.json` like the following:

> `"preinstall": "npx yalc add sf-shared && yarn --cwd ../../ copy-shared",`

or

> `"preinstall": "npx yalc add sf-ui sf-shared",`

However, renovate fails to update lock files for any package that includes a `preinstall` script with `yalc`.  Here is an example of the message we get on the renovate-created PRs:

![屏幕快照 2020-02-13 上午10 39 41](https://user-images.githubusercontent.com/15968012/74408173-2ba67900-4e4d-11ea-95a9-2d229ed46f75.png)

I would like that renovate recognized our `preinstall` scripts and runs them prior to installing so that the lock files for all of our packages can be updated.

**Comment by rarkins** [comment]
At this point we don't have a timeline for when we'll allow arbitrary scripts to be run on our hosted infrastructure, due to the extra monitoring overhead it will introduce to fend off the new attack vectors it introduces. If you want to allow scripts then you'll need to run the self-hosted version of Renovate or WhiteSource Renovate and set trustLevel=high.
