### ISSUE TITLE
How to disable pinning "engines"

### ISSUE THREAD

**Issue by leethree** [renovatebot/config-help#53]
What is the best way to disable pinning `engines`? We use it only to check if the runtime environment satisfy the minimal requirements of the project. So we don't need pin `node` etc. to specific version.

`package.json`:
```json
{
  "engines": {
    "node": "^8.9.0",
    "npm": "^5.5.1",
    "yarn": "^1.6.0"
  },
  /* ... */
}
```

`renovate.json`:
```json
{
  "extends": [
      "config:js-app",
      ":maintainLockFilesWeekly"
    ],
    "timezone": "Asia/Shanghai",
    "labels": [
      "renovate"
    ]
}
```

**Comment by rarkins** [comment]
Hi @leethree, thanks for your config. I noticed that the pinning of engines is caused by the "pinAllExceptPeerDependencies" rule inside "config:js-app" and decided that the best fix is to add engines to the pinning exclude list in that rule. Once I merge https://github.com/renovatebot/presets/pull/59 and publish the new version, you should not get pinning of any engines. I'll let you know once it's ready.

**Comment by rarkins** [comment]
I have published an update to the default presets. If you are using the hosted app then you should see an update in the next 1-2 hours, otherwise if you are self-hosted then it should take effect as soon as you run renovate next. Please reopen the issue if you don't find it's fixed.
