### ISSUE TITLE
stabilityDays not working for maven repositories.

### ISSUE THREAD

**Issue by khansuhel** [renovatebot/config-help#553]
### Which Renovate are you using?

Renovate Pro

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

There is a library in our java maven project which releases new updates almost everyday. And as a result renovatebot creates a new PR for it everyday. Now I know that this can be controlled using `stabilityDays` parameter in renovate.json but I am trying to figure out where does renovatebot look for release date of maven repositories. And what does it look for?
Has this feature been implemented for maven projects?

**Comment by rarkins** [comment]
We collect no `releaseTimestamp` value from the `maven` Datasource, therefore this feature can't work. Some research was also done here: https://github.com/renovatebot/renovate/issues/4689#issuecomment-544240762

If you have any suggestions for how to reliably get release timestamps out of the Maven datasource, please feel free to create an issue or PR in the main repo. Unfortunately until then `stabilityDays` can't be supported for Maven because we don't have timestamps to work off.
