### ISSUE TITLE
Version of NPM used by Renovate?

### ISSUE THREAD

**Issue by cbovis** [renovatebot/config-help#57]
Can you clarify which version of NPM is used by Renovate when installing packages and generating lock files? I couldn't see any details on this in the docs. My assumption would be that you use the latest version of NPM by default, do you respect NPM version in the engines section of package.json?

Thanks!

**Comment by rarkins** [comment]
We use the latest version and currently don’t have a way to use the version in engines instead

**Comment by cbovis** [comment]
Thanks for the quick response @rarkins, is there any plan to make this configurable or support engines in the future?

**Comment by rarkins** [comment]
It’s technically possible, although not easy. Are you using the hosted app, and what is your example engines value?

**Comment by cbovis** [comment]
Not to worry @rarkins, we're currently locked to v5.6.0 of npm in our engines config but are going to have a discussion about switching to the latest version of npm.

**Comment by rarkins** [comment]
Let me know if it becomes a problem. Npm 6 has some different syntax in its lockfile but is compatible with npm 5. The downside is you may see “npm install” generating a diff for an otherwise valid lockfile if you are switching back and forth. “npm ci” is recommended for dev and CI to install directly from lock file but came maybe after 5.6.0
