### ISSUE TITLE
Setting automergeType for GitHub and GitLab Projects

### ISSUE THREAD

**Issue by ghost** [renovatebot/config-help#59]
Is it possible to set `automergeType` to `branch-push` in a shared Renovate config package and use that package across GitLab and GitHub repositories?

I know `branch-push` is not supported in GitLab, but I would like to use a single Renovate configuration package between repositories and expect that Renovate will fall back to `pr` for `automergeType` for my GitLab projects.

**Comment by rarkins** [comment]
Right now the function [`mergeBranch` in GitLab](https://github.com/renovateapp/renovate/blob/9d92a958c4d817d786bdee6749a563151ee811e6/lib/platform/gitlab/index.js#L337-L339) is an empty function, so it should probably be changed to throw an exception like GitHub does if it fails to merge. In such cases a PR is then raised, and branch merging is not retried in future (it's skipped if a PR exists), but PR automerging is tried *if* there is only one "clean" commit in the branch still, which there would be. So with that one change, I think it would work, however it might still look a little ugly as we added a feature to explain in such PRs that it was created due to branch automerge failure.

Alternatives:
1. Support branch-push in GitLab (Cc @dragomirt)
2. Support github, gitlab and vsts configuration objects to allow different configuration per platform
3. Allow `platforms` as a filter in `packageRules` instead of full configuration objects (means the automerge must be configured by `packageRule` in this case)

**Comment by rarkins** [comment]
For (1), we can look at the Cherry Pick API: https://docs.gitlab.com/ee/api/commits.html#cherry-pick-a-commit

I think it might work if we have use an endpoint like `POST https://gitlab.example.com/api/v4/projects/5/repository/commits/renovate%2F/eslint-5.x/cherry_pick?branch=master`

**Comment by rarkins** [comment]
@destroyerofbuilds mergeBranch is now supported in GitLab thanks to https://github.com/renovatebot/renovate/pull/2178

FYI, I have deprecated `branch-merge-commit` and renamed `branch-push` to simply `branch`, i.e. there is only one way or merging branches now.

Please test out and confirm if this can be closed. GitLab's approach to merging branches is a little different though, but hopefully works as we intend.

**Comment by hbetts** [comment]
I can confirm that `branch` value for `automerge` option is working really well across Git platforms. Thank you!
