### ISSUE TITLE
Prettier failing on onboarding renovate.json

### ISSUE THREAD

**Issue by Bmgaynor** [renovatebot/config-help#593]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant
Yes

### What would you like to do?
Control the formatting of the `onboardingConfig`. 
When the onboarding MR is created the renovate.json file is failing [prettier](https://prettier.io/)

onboarding MR renovate.json that is failing prettier 
```json
{
  "extends": [
    "@diecs/renovate-config"
  ]
}
```

passing
```json
{
  "extends": ["@diecs/renovate-config"]
}
```

config
```js
// config.js

module.exports = {
  ...
  onboardingConfig: {
    extends: ['@diecs/renovate-config']
  },
 }

```

**Comment by rarkins** [comment]
Unfortunately this is not configurable currently. But you would be welcome to submit a PR that Prettier-ifies the onboardingConfig instead of plain stringifying it here: https://github.com/renovatebot/renovate/blob/f1d0b7b5fe6e45ae72ffb89d77c57e22ebc75431/lib/workers/repository/onboarding/branch/config.ts#L41

**Comment by Bmgaynor** [comment]
@rarkins Thanks for very timely response.
I'll look into what the expected prettier format of JSON files is and submit a PR.

**Comment by rarkins** [comment]
I think you could need to invoke prettier programmatically (and change it from devDependency to dependency)
