### ISSUE TITLE
Previous version in PR title and commit message

### ISSUE THREAD

**Issue by augi** [renovatebot/config-help#602]
**What would you like Renovate to be able to do?**
It would be great if the title of a newly created PR and commit message contained also information about the previous version. It's useful esp. in commit message because then it is obvious from changelog if it's a major version update or just a patch.

**Comment by rarkins** [comment]
commitMessage and it’s children are templates that can be modified. I think if you search this repo there might be an example or two already. See also the docs for “templates”

**Comment by augi** [comment]
Thank you for quick response! ❤️ So what I need is to change the `commitMessageExtra` configuration, for all the repositories (I'm using renovate as Docker image, for self-hosted GitHub Enterprise).

So should I set `COMMIT_MESSAGE_EXTRA` environment variable of that Docker container to something like `"from {{{fromVersion}} to {{{toVersion}}}"`?

So I have actually two questions:
1. Is it possible to set `COMMIT_MESSAGE_EXTRA` environment variable when executing the renovate Docker image?
2. Is `fromVersion` valid _variable_ to use?

Thank you! 🙏

**Comment by rarkins** [comment]
FYI, you can already tell which are major or non-major updates by looking at the commit message and PR title.

Minor ones look like this: "Update foo to v4.1.0"
Major ones look like this: "Update foo to v4"

**Comment by rarkins** [comment]
Description of template variables is here: https://docs.renovatebot.com/templates/

Setting `COMMIT_MESSAGE_EXTRA` problem isn't enough because this Docker default will override it: https://github.com/renovatebot/renovate/blob/e411a70e2d222a05e8338cbdff3270ca54e48c8e/lib/config/definitions.ts#L1462-L1463

You should either:
- Have a `config.js` or `config.json` within your bot container (e.g. mapped using volumes), or
- Use your own preset config that each of your `renovate.json` repository configs should extend

Both of the above would mean that you could configure once and then get the same setting applied throughout.

**Comment by augi** [comment]
Thank you very much for your responses, very helpful! And also thank you for this cool tool! 👍
