### ISSUE TITLE
Set fixed/sharp schedule for PRs and auto merging?

### ISSUE THREAD

**Issue by msallent** [renovatebot/config-help#613]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### What would you like to do?

I would like to set a sharp schedule (eg: every day at 9am) for all PRs.

Currently, I have it set as "before 10am" but there's no consistency at all, I had PRs for the same repo created at 00:43 (auto-merged 01:33), 00:43 (auto-merged 02:17), 00:43 (auto-merged 03:49) and 05:30 (auto-merged 06:54).

Why does auto merging take so long? Why does it sometimes take less than an hour and sometimes more than three?

My goals are:

- Start PR creation at 09:00 every day.
- Auto merge immediately (or if this is not possible, set a fixed schedule to do so, eg: exactly 1 hour later)

My current config if it's any useful:

```
{
  "extends": ["config:base"],
  "timezone": "America/Buenos_Aires",
  "schedule": "before 10am",
  "prHourlyLimit": 0,
  "labels": ["dependencies"],
  "automerge": true,
  "major": {
    "automerge": false
  }
}
```

Thank you.

**Comment by rarkins** [comment]
The hosted app works off a priority job queue, where scheduled jobs (added once per hour for all repos) are lower priority compared to jobs that result from things like PR merges. The scheduled queue doesn't always get fully serviced each hour, so sometimes it may take > 1 hour between scheduled runs.

There is no concept of any exact time or fixed schedules for running and you'll never get that unless you host your own bot. 

You'll likely notice that when one PR is automerged, the other ones need rebasing from master branch and therefore another round of tests. Based on your log, I'm guessing:

 * 00:43 - First run after 00:00 when schedule is enabled. Three PRs required and all three created
 * 01:33 - Second run. First PR was automerged, so Renovate stops further updates this run as it knows master has changed
 * 01:?? - Another run probably happened here, because automerging triggers a webhook that queues a high priority job. PRs B and C probably rebased
 * 02:17 - Another scheduled run. PR B automerged.
 * 02:?? - Another run triggered by the webhook probably rebased PR C
 * 03:49 - Another scheduled run. PR C automerged
 * 05:30 - Another scheduled run. PR D (probably a recent release) was created
 * 06:54 - Another scheduled run, PR D automerged.

If you are interested you can probably look at the logs one by one in app.renovatebot.com to confirm the above.

If you understand git, you would know that what you ask for is unlikely to be practical at all times because of merge conflicts. It's also a good idea to rebase other PRs after an automerge to make sure they function fine with the updated dependency from the automerged PR. If you want them altogether, then define a grouping rule and hope for the best (i.e. because one bad upgrade will mean you can't merge the PR).

**Comment by msallent** [comment]
Those are some really good points that I hadn't thought about. In fact, now that you say it, it makes total sense how the bot works.

Anyways, I switched to `automergeType: 'branch'` so I don't get emails anymore.

Thanks for taking the time to write out a detailed answer!
