### ISSUE TITLE
Renovate gets registry-failure timeouts almost on every run

### ISSUE THREAD

**Issue by freiksenet** [renovatebot/config-help#619]
We are using renovate for https://github.com/gatsbyjs/gatsby. Here is our config https://github.com/gatsbyjs/gatsby/blob/master/renovate.json5

### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevantn

We get timeouts of npm registry requests. It retries, but eventually almost always fails. We got this timeouts after we added more repositories to scan to our config.

### What would you like to do?

We need help figuring out how to make it work or for a workaround. Eg if updating those new dependencies manually would help renovate (we added some examples that have been long without npm update).

**Comment by rarkins** [comment]
We are seeing npm timeouts in the app and have not been able to determine the root cause, even with some help by npm when their team was a bit bigger prior to acquisition. It seems correlated with large manifests and certain ones seem to have a much higher failure rate than others.

If you check the logs (app.renovatebot.com) you will see warnings for `"Retrying npm error"` and with the dependency identified. Worst case if you update those ones *manually* it might help the rest of lookups to pass.

Meanwhile I'll keep trying a few things again to see if any help out, e.g. increasing timeouts, reducing concurrency, etc.

**Comment by rarkins** [comment]
I see that the gatsby repo seems to now be working on multiple runs in a row, please let me know if you see anything again.

**Comment by freiksenet** [comment]
Thank you for looking at this @rarkins! I guess it was a periodic issue with npm.
