### ISSUE TITLE
Default hourly limits are a bit weird if you’ve got a lot to do upfront

### ISSUE THREAD

**Issue by ticky** [renovatebot/config-help#62]
Hi there!

Renovate, in buildkite/frontend#445, noted that it would create 66 PRs, and that it would do at most 2 per hour, which means it’ll take at least 33 hours to process this group of changes.

While I appreciate that this limit is probably reasonable in the normal use case, this is kind of absurd when initiating Renovate (and yes I realise this means we’ve been bad about dependency bumps!)

I wonder if Renovate could offer to process a bigger chunk of what’s pending initially, but keep the 2-per-hour limit in longer-term usage?

**Comment by rarkins** [comment]
@ticky this default limit was actually added because of people being frustrated at their *CI* being swamped when initiating Renovate. e.g. People using CircleCI or Travis may only have 1-2 concurrent processes and Renovate ended up swamping the build queue so that "regular" PRs took forever to reach the front and get built. This default limit is not there to protect Renovate.

You can easily override this option to be unlimited permanently, e.g. as @toolmantim has done here: https://github.com/buildkite/site/blob/978e192bef2d246e51b77b169e1d10337d7066a7/renovate.json#L5

FYI there is also a default concurrent limit of 20

**Comment by ticky** [comment]
That’s fair, and I did end up copying what Tim did. 😄

Perhaps a warning when the “things to do” list is significantly bigger than the limit would be helpful in that case!

Thanks for the quick feedback 😊

**Comment by rarkins** [comment]
Moving Tim's suggestion to https://github.com/renovatebot/renovate/issues/2234
