### ISSUE TITLE
Updating peerDependencies

### ISSUE THREAD

**Issue by moltar** [renovatebot/config-help#620]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

I'm using `npm`.

I have the following:

```json
{
  "devDependencies": {
    "@foo/config": "1.5.1"
  },
  "peerDependencies": {
    "@foo/config": "^1.5.1"
  },
}
```

When `@foo/config` got updated, Renovate picked that up and updated it in `devDependencies`, but not in `peerDependencies`.

What do I need to setup to automatically match `devDependencies` and `peerDependencies`?

Thanks!

**Comment by rarkins** [comment]
If `@foo/config` was updated to e.g. `1.5.2` then it still satisfies the `peerDependency` range of `^1.5.1` so that's why it's not updated. Usually people want to keep peerDependencies as wide as possible.

I suggest either:
1. Change the peer to be non-range too, or
2. Configure [rangeStrategy](https://docs.renovatebot.com/configuration-options/#rangestrategy) to be `"bump"` for peerDependencies:

```json
{
  "packageRules": [{
    "depTypeList": ["peerDependencies"],
    "rangeStrategy": "bump"
  }]
}
```

You could specify the specific package name there too if you want it to apply only to that package

**Comment by moltar** [comment]
@rarkins Thank you for the explanation! :)
