### ISSUE TITLE
Unclear how reconfiguration is intended to be tested

### ISSUE THREAD

**Issue by ticky** [renovatebot/config-help#63]
Renovate’s onboarding PR is great, but I’ve now realised I want to change some configuration post-merge, and it’s unclear whether I should be creating a `renovate/something` branch to get Renovate’s attention and let it describe it to me, or if I’m just supposed to commit it to the primary branch and trust in my ability to write valid JSON 😜

**Comment by rarkins** [comment]
Unfortunately an interactive "Reconfigure Renovate" PR is not supported yet - feature request is https://github.com/renovatebot/renovate/issues/547

However, Renovate *does* do a little trick if you create a PR with Renovate in its title (e.g. you call it "Reconfigure Renovate" yourself). In that case, every time Renovate runs it will look for any PRs with Renovate in its title and which modify `renovate.json` and if so then it will run its validation against it and set a green status check if it passes or a red one if it fails. So it's not interactive but it's at least it's validating.

Note: Do not create any branch with the same branchPrefix as renovate uses as otherwise it will assume it's one of its own and clean it up if it doesn't think it is necessary.

A final option - maybe ok if you have none or just a few PRs open is to do this:

1. Find and rename the original Configure Renovate PR (e.g. add " - old" to its title)
2. Delete the `renovate.json` from master

This will trick Renovate into thinking it never onboarded the repository at all, and you will get a new Configure Renovate PR that you can interactively edit again.

**Comment by ticky** [comment]
> However, Renovate does do a little trick if you create a PR with Renovate in its title…

Ah! That is cool. Is this in the docs somewhere? If it is I missed it entirely!

> Note: Do not create any branch with the same branchPrefix as renovate uses as otherwise it will assume it's one of its own and clean it up if it doesn't think it is necessary.

😅 good to know!

> This will trick Renovate into thinking it never onboarded the repository at all

Possibly a little too hardcore, haha!

I’ll be curious to see what you come up with for this in future :)
