### ISSUE TITLE
How to configure a monthly schedule *except* for some packages which should always be instant?

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/config-help#64]
I see that `schedule` allows me to set it to `monthly`. However, we have a few own private npm packages which we always want to be updated instantly as soon as there is a new release published. How would I accomplish this? Set `schedule` to `monthly`, then add a package rule for the packages of our npm org and set `schedule` to an empty array? Or `null`?

**Comment by felixfbecker** [comment]
Hmm, I tried that and it doesn't seem to work. I just released a new version of an internal package, I see in the logs that Renovate detected that update and determines a branch and PR to be created, but then doesn't seem to act on it. Other dependencies are being checked for the monthly schedule and dont pass it, but I don't see any logs for schedule checking at all for the internal package. I send you the logs per email.

**Comment by rarkins** [comment]
Looking at the logs, I think I know what's going on.

- Renovate needs to "Pin Dependencies" first so has a PR planned for that
- Pin Dependencies PR is not raised because of the schedule
- Because Pin Dependencies is present, remaining PRs are held up waiting

It's intentional to hold back other PRs until the Pin Dependencies PR is complete, otherwise we might create a large number of PRs up front that then all need to be recreated once the pin PR is merged. Obviously though in this case it's resulting in an unintended side effect.

I'm thinking through possibilities:

1. Update config to add `:preserveSemverRanges` for now so that the Pin Dependencies PR is not raised and others may continue
2. Remove the monthly default schedule long enough that the Pin Dependencies PR can be raised. Then add back the monthly schedule before merging it.
3. Add a package rule that ensures "pin" PRs always skip schedules

(3) is something I could maybe even do as part of the `config:base` preset, if you think that makes sense.

**Comment by felixfbecker** [comment]
That sounds like a bug to me, because I only configured one package rule (`@types`) to use `pinVersions: true`. So I would not expect the other package rules do be blocked by the pin-versions-PR by that rule.

**Comment by rarkins** [comment]
I reworked the pin blocking logic so that it only blocks PRs that are relevant. i.e. if some `@types` needs pinning then it won't hold up `@sourcegraph/*` packages that do not. I also added an override so that Pin Dependencies PRs override configured schedule too, because they should be raised/merged immediately anyway to establish the correct baseline.

**Comment by felixfbecker** [comment]
So the updates do happen, but it's less "immediate" than I thought - it usually takes more than an hour for the PR to get opened. I gave the GitHub app access to all repos and added the renovate npm user to our org, so I expected it to instantly trigger a run on a new release through some kind of webhook. Is it expected to take that long?

**Comment by rarkins** [comment]
@felixfbecker are these "internal" releases of private scoped packages?

**Comment by felixfbecker** [comment]
Not sure what you mean by "internal"? They are private scoped packages, yes. The release is published to npm and a GitHub release + git tag is created too.

**Comment by rarkins** [comment]
npm doesn’t include private modules in its follower feed so that’s why it’s not triggering a run in real time. It would need 
https://github.com/renovatebot/renovate/issues/2301 implemented - suggestions welcome there.
