### ISSUE TITLE
I'm using config base and it's not updating even if a new version is available

### ISSUE THREAD

**Issue by happysalada** [renovatebot/config-help#66]
Is there something I need to set so that it creates a PR automatically ?
when I run `yarn upgrade --latest` I can see there is a new patch for webpack (in my devDependency).
What is the additional setting I need to activate to get renovate bot to make a PR ?
Or does it only update once per week ?

**Comment by rarkins** [comment]
By default Renovate runs all the time. If this is for a public repository, please provide a link. If private, please provide:

- Your `renovate.json` config
- Extract of your `package.json` (e.g. including what the value for `webpack` is).

You might also want to look at https://renovatebot.com/dashboard first and see if the logs give you a hint as to what's going on.

**Comment by rarkins** [comment]
If there are package.json files in those directories then it should be possible already but I assume there isn’t or it would be working already. What is in takes directories and what does the lock file entry look like for each?

**Comment by happysalada** [comment]
the deps directory contains all my backend dependencies so It is included in the .gitignore file. That is why it's not finding the package.json in those sub-folders of deps.

Is there no way to tell renovate to ignore those two packages entirely?
If possible I don't want to commit my backend dependencies to my git repo.

(PS: I have a standard setup for Phoenix, the web framework for elixir, if we manage to solve the problem for me, it should help others.)

**Comment by rarkins** [comment]
Renovate is happy to ignore the missing files, but `yarn` is not. It's `yarn install` that is failing because your `package.json` refers to a directory that doesn't exist when it runs.

Please locate the entry for these folders in `yarn.lock` and copy/paste it here into the issue.

**Comment by happysalada** [comment]
Here are the relevant entries
```
"phoenix@file:../deps/phoenix":
  version "1.3.3"

"phoenix_html@file:../deps/phoenix_html":
  version "2.11.2"
```

**Comment by rarkins** [comment]
It looks like those folders have package.json files in them, which makes it harder. 

Before we go further, I’d like to understand *why* it’s done this way, because right now I do not. How do you “install” Phoenix and phoenix_html before running “yarn install” and why don’t you just include them as regular dependencies in the main package.json?

**Comment by rarkins** [comment]
@happysalada why wouldn't it work if you just added them as regular dependencies in the `package.json`? Right now you have added them as "dependencies" anyway, albeit from file. What would go wrong if you installed them directly from the npm registry?

**Comment by happysalada** [comment]
Ok, I have installed them from NPM, good idea!
The latest versions haven't been published, but I can live with that.
Renovate updated my babel dependency but not my webpack dependency. 
4.15.1 => 4.16.0
Maybe it takes a bit longer.
Anyway, thanks a lot for the help!

**Comment by rarkins** [comment]
Thanks for the update. Config:Base limits itself to max 2 new PRs per hour so that might be the cause.

**Comment by jimsynz** [comment]
This has bitten me too. Unfortunately the `package.json` that is generated by `mix phx.new` includes this as the default configuration - although most people are using `npm` and not `yarn` which I assume is why other folks aren't seeing this problem.  I can't think of another way of nicely keeping the javascript client libraries in sync with the server Phoenix version.  @rarkins is there any way we can run a command before `yarn` is run (so that we can do `mix deps.get` in the parent directory)? I can't see anything in the docs.
Maybe @chrismccord or @josevalim can chime in here with an explanation of why the JS dependencies are done this way? I assume it's to keep the versions in sync, but I'm not 100% sure.

**Comment by viceice** [comment]
@jimsynz please open a new issue and fill the template. Also provide a minimal public repo for reproduction.
