### ISSUE TITLE
No PRs for updates which are removed from commit history

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/config-help#663]
If a branch is force-pushed, in effect removing a previously merged update, Renovate doesn't appear to raise a PR to correct this.
Is there a way to force this behaviour?

**Comment by rarkins** [comment]
Renovate won't by default re-create a PR that has already been merged or closed. I don't think force pushing changes anything, e.g. it could also be reverted or manually rolled back.

You should see a PR comment added noting that the old one is blocking an update.

You can:
- Rename the blocking PR to have it raised again, or
- Use `masterIssue` so that you have visibility of it and can force it to be recreated

**Comment by ChipWolf** [comment]
Solved with `masterIssue`
