### ISSUE TITLE
Mono-repo setup with bump and pin rangeStrategy

### ISSUE THREAD

**Issue by austin94** [renovatebot/config-help#69]
:wave: I'm currently trying to add renovate into a lerna-based mono-repo, [Zendesk Garden](https://github.com/zendeskgarden/react-components). Here is the [configuration PR](https://github.com/zendeskgarden/react-components/pull/63) for some background.

## Background

We currently maintain a mono-repo of React components that uses lerna to manage the inter-dependencies.

I've started a basic configuration above, but am wondering if you know of any good tips/tricks to help achieve what were looking for:

### Global Dependencies
- The root `~/package.json`
  - We would like to have these be `pinned` and have all minor/patch updates grouped into a single PR, with major updates being split into their own

### Package Dependencies
This is where it gets unique:

- Each individual package `~/packages/*/package.json`
  - Ignore **all** internal packages (`@zendeskgarden/react-*`) as lerna will manage those for us
  - Ignore `peerDependencies` as we will want to manage these ourselves
  - Pin all `devDependencies` with the major/minor updates grouped together
  - Use the `bump` strategy for all `dependencies`

We mark all `dependencies` as external for consumers which is why we're looking to keep them open `^`.

(we also have an `examples` directory that we will eventually want to keep updated as well, but that should be simple after we get the packages correct)

## Other Repos

Once we get this repo configured we will want to add this to our other mono-repo [css-components](https://github.com/zendeskgarden/css-components) and 4 other standard repos.

Thanks in advance for any insights you might have about this! (also, renovate is super cool)

## Current Config

```
{
  "extends": [
    "config:base"
  ],
  "schedule": "before 3am every 2 weeks",
  "rebaseStalePrs": true,
  "packageRules": [
    {
      "depTypeList": [
        "peerDependencies"
      ],
      "enabled": false
    },
    {
      "packagePatterns": ["^@zendeskgarden/react"],
      "groupName": "lerna-internal",
      "enabled": false
    },
    {
      "paths": ["packages/**"],
      "groupName": "react-packages"
    },
    {
      "paths": ["package.json"],
      "groupName": "lerna-packages",
      "minor": {
        "groupName": "all non-major dependencies",
        "groupSlug": "all-minor-patch"
      },
      "rangeStrategy": "pin"
    }
  ],
  "reviewers": [
    "austin94",
    "ryanseddon",
    "jzempel"
  ]
}
```

**Comment by rarkins** [comment]
> The root ~/package.json
>  - We would like to have these be pinned and have all minor/patch updates grouped into a single PR, with major updates being split into their own

You should find that dependencies in the root `package.json` are pinned already because:
- They are all `devDependencies`
- You have extended `config:base`
- `config:base` sets `rangeStrategy` to `auto`, which means `devDependencies` are pinned *everywhere*

But it doesn't hurt to explicitly define rangeStrategy=pin like you've done.

If you do this:
```
    {
      "paths": ["package.json"],
      "groupName": "lerna-packages",
      "minor": {
        "groupName": "all non-major dependencies",
        "groupSlug": "all-minor-patch"
      },
      "rangeStrategy": "pin"
    }
```

Then it means you'll get two groups - "Update all non-major dependencies", and "Update lerna-packages" which contains all major updates grouped together. I suspect you instead wanted major updates to be separated into individual PRs? If so then remove the `"groupName": "lerna-packages",` line.

> Ignore all internal packages (`@zendeskgarden/react-*`) as lerna will manage those for us

Renovate should automatically ignore all internal packages, i.e. it scans every `package.json`, looks for the `name` inside each, and then ignores that name across the entire Lerna project. You should not need the package rule you've added, assuming that all these packages are correctly named inside `package.json` files.

> Ignore `peerDependencies` as we will want to manage these ourselves

I think the package rule you have added should do the trick to disable them.

> Pin all devDependencies with the major/minor updates grouped together

Could you clarify what you mean here? Do you mean all updates - no matter what - grouped into a single PR, or two PRs (one for minor, one for major), or something else?

> Use the bump strategy for all dependencies

Are you sure that's what you want? You also mention:

> We mark all dependencies as external for consumers which is why we're looking to keep them open ^.

Using the "bump" strategy means that although you specify ranges, the range is kept up to date with only the very latest version. e.g. instead of `^1.0.0` meaning any 1.x version you would end up with `^1.5.1` when `v1.5.1` is the latest release, which is essentially just as pointless as if you pinned the dependency.

**Comment by austin94** [comment]
> Renovate should automatically ignore all internal packages, i.e. it scans every package.json, looks for the name inside each, and then ignores that name across the entire Lerna project.

This is true that it recognizes not to update them, but they are still `pinned` during the initial PR because they're `devDependencies`. I'm honestly not sure if lerna continues to bump them if they're missing the range semVer, but I'm just going to leave it the same for continuity right now.

> I suspect you instead wanted major updates to be separated into individual PRs?

That is correct. Removed.

> Could you clarify what you mean here? Do you mean all updates - no matter what - grouped into a single PR, or two PRs (one for minor, one for major), or something else?

Sorry, butchered that sentence. What I was playing around with is having minor/patch updates for _ALL_ of the internal packages be grouped into a single PR.  I think I got a working example with the config below.

> Using the "bump" strategy means that although you specify ranges... which is essentially just as pointless as if you pinned the dependency.

Haha I didn't read the documentation as closely as I should have. Since we manually keep these as low as possible to allow a range for our consumers, I've `disabled` them for now.

### New Config

```json
{
  "extends": [
    "config:base"
  ],
  "schedule": "before 3am every 2 weeks",
  "rebaseStalePrs": true,
  "packageRules": [
    {
      "depTypeList": [
        "peerDependencies",
        "dependencies"
      ],
      "enabled": false
    },
    {
      "packagePatterns": ["^@zendeskgarden/react"],
      "groupName": "lerna-internal",
      "enabled": false
    },
    {
      "paths": ["packages/**"],
      "groupName": "react-packages",
      "minor": {
        "groupName": "all package non-major dependencies",
        "groupSlug": "lerna-packages-minor-patch"
      }
    },
    {
      "paths": ["package.json"],
      "minor": {
        "groupName": "all development non-major dependencies",
        "groupSlug": "dev-minor-patch"
      }
    }
  ],
  "reviewers": [
    "austin94",
    "ryanseddon",
    "jzempel"
  ]
}
```

This config seems to be along the lines of what we were looking for. Thanks for the help!

Unrelated, but did the bot markdown template update recently? The new layout is 🔥

**Comment by rarkins** [comment]
> Unrelated, but did the bot markdown template update recently? The new layout is 🔥

Yes, I've been playing with it in the last few days in an effort to make it a bit more streamlined and intuitive.

If you have any schedule, that's what will take effect as soon as you activate. Perhaps you can remove it initially until the initial flow is over and then add it back again? Also, I'm not certain that the "every two weeks" option will work as you'd expect - Renovate uses a subset of a third party library for time parsing.

I have a special rule where the initial Pin Dependencies PR is not held up by schedules, so that explains why you saw it already.

If you go to https://renovatebot.com/dashboard you'll probably see messages about it skipping branch creation because not in schedule. I plan to support a "request job start" option in that dashboard one day, but that still wouldn't fix the schedule problem. It would need a "request job start" with option to "ignore all schedules" or something like that in your case. For now I recommend dropping the schedule until you're happy with the ones remaining.
