### ISSUE TITLE
Comment specific message when PR is opened

### ISSUE THREAD

**Issue by SofiaGR** [renovatebot/config-help#703]
### Which Renovate are you using?

Not sure, set up by company as a bot

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

Is it possible to have renovate itself comment a message such as '[build-x]' when it opens the PR?

**Comment by rarkins** [comment]
Do you mean you want Renovate to submit a PR and then to comment on its own PR immediately?

If so, the only comment Renovate is able to make currently is for auto merging and designed to work with the `bors` bot. You can search `prComment` documentation to see if that fits, otherwise the answer is no.

**Comment by SofiaGR** [comment]
> Do you mean you want Renovate to submit a PR and then to comment on its own PR immediately?
Yeah

> If so, the only comment Renovate is able to make currently is for auto merging and designed to work with the `bors` bot. You can search `prComment` documentation to see if that fits, otherwise the answer is no.
Ok, then it doesn't have what I need to automate that comment 😅 

Thank you!
