### ISSUE TITLE
`semanticCommits: true` is ignored

### ISSUE THREAD

**Issue by ynnoj** [renovatebot/config-help#712]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

Firstly, thank you for such an awesome service! I'm using the automated dependency bot in conjunction with [`semantic-release`](https://github.com/semantic-release/semantic-release) to publish packages. However I'm struggling to configure the bot to use the correct commit conventions to *NOT* trigger a release with the `semantic-release` CLI. Below is my config:

```json
{
  "automerge": true,
  "extends": ["config:base", "schedule:weekly"],
  "major": {
    "automerge": false
  },
  "reviewers": ["ynnoj"],
  "semanticCommits": true
}
```
Reading the docs, enabling [`semanticCommits`](https://docs.renovatebot.com/configuration-options/#semanticcommits) should force all PRs/commits to be prefixed with `chore`. However PRs continue to be prefixed with `fix` (see [here](https://github.com/ynnoj/gatsby-source-printful/pull/30) for a recent example).

Please help my understand where in my config the issue lies. Thanks!

**Comment by rarkins** [comment]
You've extended [config:base](https://docs.renovatebot.com/presets-config/#configbase) which itself extends [:semanticPrefixFixDepsChoreOthers](https://docs.renovatebot.com/presets-default/#semanticprefixfixdepschoreothers). It uses `packageRules` so that's taking precedence. You could do something like this to override it:

```json
{
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "semanticCommitType": "chore"
    }
}
```

Alternatively you could add `"ignorePresets": [":semanticPrefixFixDepsChoreOthers"]` to your config so that that rule is ignored to begin with.

**Comment by ynnoj** [comment]
@rarkins Thanks! I've updated my configs and will await PRs on Monday 🤞

**Comment by rarkins** [comment]
I also recommend enabling “masterIssue” as it gives you visibility and control of scheduled PRs
