### ISSUE TITLE
Custom commit messages

### ISSUE THREAD

**Issue by hisener** [renovatebot/config-help#718]
### Which Renovate are you using?

Renovate Open Source CLI (using the docker image `renovate/renovate:21.13.3-slim`)

### Which platform are you using?

GitHub.com (without GitHub App)

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

My question is somewhat related to https://github.com/renovatebot/config-help/issues/520. In that issue, I asked if it's possible to use separate commits in a single upgrade PR. We decided to go for separate PRs and it's going well so far.

However, we want to keep our old commit message structure which I described in https://github.com/renovatebot/config-help/issues/520#issuecomment-584030831. For this purpose, I've create a simple script to generate those commit messages and add them as a comment. You can see an example in https://github.com/PicnicSupermarket/oss-parent/pull/37#issuecomment-648201083. But this approach is prone to errors, for instance, some developers do not pay attention to this comment and merge the PR with default Renovate commit.

So, I am looking for a configuration to modify commit messages within Renovate rather than a separate script. I've checked https://github.com/renovatebot/renovate/blob/master/lib/util/template/index.ts and thought maybe we could register a helper and invoke my custom script but looks like handlebars does not support async functions. I wonder if there is already a solution for this problem. Thanks in advance.

**Comment by rarkins** [comment]
Renovate supports customizing [commitMessage](https://docs.renovatebot.com/configuration-options/#commitmessage) as well as the commit body, although we recommend you try to stick to customizing the separate components of `commitMessage` if possible. Is there anything holding you back from that?

Using your example `Upgrade PostgreSQL JDBC 42.2.13 -> 42.2.14 (#37)`

If you do a merge squash then the ` (#37)` part will be appended by GitHub at time of merge. 

The `42.2.13 -> 42.2.14` obviously looks possible because we have something similar in the PR body's table.

How would you autogenerate `PostgreSQL JDBC` ?

**Comment by hisener** [comment]
Yes, I do already use those options:

```
    commitMessageAction: Upgrade',
    commitMessageTopic: '{{depName}}',
    commitMessageExtra: '{{fromVersion}} -> {{toVersion}}',
```

I could also use `commitBody` but at the moment to generate that information my script calls GitHub API.

> How would you autogenerate PostgreSQL JDBC ?

At the moment, I do use a lookup table for human-readable names, some extra information, and GitHub repository details. `PostgreSQL JDBC` comes from there.

I use GitHub repository owner and name to find releases (fallbacks tags if there is no release). The generated suggested commit message body contains extra info (`https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md` in this case) and releases if there is any and GitHub diff comparison link. The result looks like the following:

```
Upgrade PostgreSQL JDBC 42.2.13 -> 42.2.14

See:
- https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md
- https://github.com/pgjdbc/pgjdbc/compare/REL42.2.13...REL42.2.14
```

**Comment by hisener** [comment]
^ I guess this is so specific use-case and it is not feasible to find a generic solution. So, I think I should reduce the scope of my question. :) Is there any way to introduce a way to generate a custom commit message rather than using renovate's flow. As I said in the issue, I checked handlebars, maybe a helper would work, something like `{{customCommitMessage}}`. So that renovate can call the provided function in the config file. But handlebars don't support async functions. 🤷‍♂️

**Comment by rarkins** [comment]
It's not currently planned to call generic functions, although for self-hosted users it's a feasible future functionality. What I'd prefer is that Renovate itself can gather the information you require, e.g.

- Our changelog fetching function could return a direct link to the filename it found
- Generating compare links is something similar to what we already do, but we could be better at it
- We could perhaps have some type of community-contributed list of aliases/friendly names, e.g. `org.postgresql:postgresql` -> `PostgreSQL JDBC`

BTW the table you see in PR bodies is customizable so that would probably be another good location to embed this.

**Comment by hisener** [comment]
> Our changelog fetching function could return a direct link to the filename it found

👌 

> Generating compare links is something similar to what we already do, but we could be better at it

How about individual release links? For example https://github.com/PicnicSupermarket/oss-parent/pull/26#issuecomment-640677123. It is also useful to have separate release note links.

> We could perhaps have some type of community-contributed list of aliases/friendly names, e.g. org.postgresql:postgresql -> PostgreSQL JDBC

I like the idea of "community-contributed list of aliases/friendly names". 👌 

For Java libraries, we could also fall back to the name specified in `pom.xml`. For instance, `postgresql`, https://search.maven.org/artifact/org.postgresql/postgresql/42.2.14/jar -> `PostgreSQL JDBC Driver`.

> BTW the table you see in PR bodies is customizable so that would probably be another good location to embed this.

Do you mean this table?

```
| Package | Update | Change |
|---|---|---|
| com.google.guava:guava | major | `28.0-jre` -> `29.0-jre` |
```

I will check existing fields listed [here](https://docs.renovatebot.com/templates/) again.

**Comment by rarkins** [comment]
> How about individual release links?

The list could get quite lengthy however it's probably feasible for us to expose that type of thing if you wish to use it.

> Do you mean this table?

yes, that one. `prBodyColumns` etc
