### ISSUE TITLE
Separate MR for the same artifact used in different files

### ISSUE THREAD

**Issue by grzesuav** [renovatebot/config-help#734]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?
Hi, I have several dependency files, in which I use the same dependency (let's say there are dockerfiles, all having `FROM alpine 3.11`) - renovate creates single MR to bump `alpine 3.11` to `alpine 3.12` in all dockerfiles - I would want to configure it to make different MR for different files. Is that possible ?

**Comment by rarkins** [comment]
To make them into separate MRs means you need to get them into separate branches. Branches are typically based on the dependency name and that's why they go into the same branch/MR. Search this repo's closed issues for `parentDir` for one way to achieve branch separation. That way the branch is based on the parent directory name + dependency name. Otherwise if that automated approach doesn't work you may need to manually specify the branchPrefix for various files to ensure they are separated.

**Comment by grzesuav** [comment]
thanks @rarkins will try that and see if it works. Will close the issue once solved

**Comment by grzesuav** [comment]
it worked, thank you :)
