### ISSUE TITLE
Renovate is disabled

### ISSUE THREAD

**Issue by jugaltheshah** [renovatebot/config-help#78]
Hello,

I was trying to configure Renovate for a project in my org. Our preference is to use a section in package.json instead of renovate.json, so I deleted the renovate.json file and updated the renovate/configure branch (initial branch that the bot creates). I then got an email saying "Renovate is disabled due to lack of config". This makes sense as there is no config at that point, but now I'm having a hard time getting Renovate to do things on this project again. Even after making a few more commits to the branch, it does not update the "What to Expect" section. Here's what I've tried/confirmed so far:

1) Confirmed that the Renovate bot still has access to the repo.
2) Created another commit to the renovate/configure branch with a `renovate` section in `package.json`
3) Per [this issue](https://github.com/renovatebot/config-help/issues/54), tried to rename the PR to "Configure Renovate - OLD" so the bot detects it as a repo needing config.

Nothing seems to want to work! How do I make Renovate start working its magic again?

Edit: also -- for future reference, was the issue that I deleted renovate.json without having a section in package.json? What is the correct way to delete it, should I just make sure I have a renovate section in package.json, and it will get picked up?

**Comment by rarkins** [comment]
Hi,

Renovate runs if there is config in the base branch (which is usually `master`). It considers a repository to be disabled if the onboarding PR has been closed, and no config exists - so this is what happened. Once a repository is considered disabled, it's then checked only once per day.

If you had added the config to `package.json` before removing it from `renovate.json` - or done it together in a single commit/PR - then it would have worked. Alternatively, if you had renamed the "Configure Renovate" PR *before* deleting the `renovate.json` then that would have "reset" the bot and you get a new onboarding PR. Adding config to `renovate/configure` branch doesn't do anything because the PR attached to that branch was already merged.

Hopefully by now the daily check of disabled repositories was already triggered. If not, please let me know the repository name and I can force a new run instead. Sorry for the confusion!

**Comment by jugaltheshah** [comment]
Sorry I should have specified, in this case, the initial renovate/configure branch PR was never merged. We are in the process of getting everything to our liking before merging. With that said though, it seems the same behavior still holds, as I deleted `renovate.json` and committed before creating a renovate section in `package.json`.

Unfortunately the disabled repo check has not triggered yet (I committed to the branch 20 hours ago, so i guess it would trigger in the next 4 hours). May I email you the repo name?

Thanks for the clarification!

**Comment by rarkins** [comment]
Yes, please email support with the repo name. The best thing you can do now is trigger a new onboarding PR:

1. Save any config you've created to clipboard or a text file
2. Find and rename any previous "Configure Renovate" PR
3. Delete any `renovate/configure` branch
4. Delete any Renovate configuration added to `master` branch (doesn't sound like you have any)

**Comment by rarkins** [comment]
@jugaltheshah please send the repository name by email if you still need help
