### ISSUE TITLE
Pushing fix-ups to renovate PRs

### ISSUE THREAD

**Issue by djmitche** [renovatebot/config-help#818]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com
### Have you checked the logs? Don't forget to include them if relevant

I don't think they are relevant here.

#### Background

We are [trying](https://github.com/taskcluster/taskcluster/pull/3414) to work around `yarn`'s habit of only updating direct dependencies, which means that we end up with several copies of commonly-used libraries like lodash, even though a single version would satisfy all requirements.  We're using a silly little [library I wrote to do it](https://classic.yarnpkg.com/en/package/yarn-minify).  Note: this issue is not about getting renovate to do this for me (and I'm active on the yarnpkg issue on the topic).

In a separate repo, [tc-admin](https://github.com/taskcluster/tc-admin), renovate doesn't know how to run `pipupdate`, so renovate PRs don't pass on the first try.

The strategy we've adopted in `tc-admin` is to pull the PR branch, run `pipupdate`, and push the change ([example](https://github.com/taskcluster/tc-admin/pull/136)).  Historically I've noticed that if I `git commit --amend` and `git push --force`, renovate will immediately force-push its own commit again, but if I make a new commit, renovate will leave it alone.  In fact, renovate would [comment on the PR in this case](https://github.com/taskcluster/tc-admin/pull/113#issuecomment-650572681).

It seems that a recent change has modified this behavior, and not in a useful direction.  In [this PR](https://github.com/taskcluster/taskcluster/pull/3393), I pulled the changes, ran the minification, and pushed a new head commit with the comment `yarn-generate`.  It seems that renovate didn't like that and force-pushed its own commit again.

#### Request

The general problem, then, is that renovate PRs as-created are not ready to merge.  What's the recommended way to address that?

**Comment by djmitche** [comment]
Minor update: https://github.com/taskcluster/tc-admin/pull/139 shows that renovate doesn't automatically force-push over the changes, so it seems that it only force-pushes when it rebases the PR.

**Comment by djmitche** [comment]
That said, we have

> :recycle: Rebasing: Never, or you tick the rebase/retry checkbox.

set on the Taskcluster, repo, so it shouldn't be rebasing..

**Comment by rarkins** [comment]
> Historically I've noticed that if I `git commit --amend` and `git push --force`

Yes, this would definitely fool Renovate into thinking the branch is unmodified and free to be force-pushed.

> if I make a new commit, renovate will leave it alone. In fact, renovate would [comment on the PR in this case](https://github.com/taskcluster/tc-admin/pull/113#issuecomment-650572681).

Also intended.

Renovate shouldn't force-push over a branch if the last git author was not itself. If it checks the previous branch and the git author matches itself, it assumes it's its own unmodified branch and can do what it wants with it. If you are able to work out steps to reproduce it doing what it shouldn't, I'd definitely want to fix it. In theory, the following should happen:
- Renovate creates the branch with a single commit
- 0..n times it decides the branch needs an update (either because its conflicted, or newer versions available, or rebase settings say the branch should be up to date) then it will force push a new single commit
- If any person or other bot adds a commit, Renovate still permanently stop rebasing and add a pr comment

There should be no scenario where it essentially says "how dare you touch my branch" and force pushes over the top of you.

> It seems that a recent change has modified this behavior, and not in a useful direction. In [this PR](https://github.com/taskcluster/taskcluster/pull/3393), I pulled the changes, ran the minification, and pushed a new head commit with the comment `yarn-generate`. It seems that renovate didn't like that and force-pushed its own commit again.

Unfortunately with force-pushing it can be hard to extract the history, e.g. all I see is this:

![image](https://user-images.githubusercontent.com/6311784/90853653-07d36b00-e37b-11ea-850a-931e49cef270.png)

I would say though that the rebase=never seems to be getting ignored.

Also a note: possible that this is partly caused by the "forking renovate" setup, because it needs to juggle two users (forking-renovate[bot] and renovate-bot) and two repos (original and fork).

If you can reproduce the force pushing when never, we'll fix that part as a bug first and maybe uncover something else in the process.

**Comment by rarkins** [comment]
Actually I'm also confused by the "never" rebase, because your config has `"rebaseConflictedPrs": false,` which means it should rebase when conflicted. FYI we migrated to a hopefully more understandable way off configuring this: https://docs.renovatebot.com/configuration-options/#rebasewhen

Relevant code: https://github.com/renovatebot/renovate/blob/53ca91301f6a36c0c87e7d6b06b1bd8c9ec1b283/lib/workers/pr/body/config-description.ts#L44-L52
