### ISSUE TITLE
React concurrent gets upgraded to react from 2016...

### ISSUE THREAD

**Issue by AdrienLemaire** [renovatebot/config-help#846]
**What Renovate type, platform and version are you using?**

Using the Github marketplace app

**Describe the bug**
React concurrent is a 16.X minor release that was expected in 2019 Q2, and still hasn't been released as stable so far (although used in production in facebook's website).
Their versioning includes the `-experimental-` substring, and renovate doesn't understand it, trying to upgrade to v0.14, which is 4 years old.

![](https://i.imgur.com/5RBgH2N.png)

Please make renovate experimental aware, only upgrading the experimental branch and newest minor version of react.

**To Reproduce**

Install react concurrent, wait for renovate to trigger an upgrade.

**Comment by viceice** [comment]
@AdrienLemaire you need to configure [`followTag`](https://docs.renovatebot.com/configuration-options/#followtag) to `experimental` if you want to follow the react experimental releases, otherwise renovate will follow `latest` which points to `16.13.1` which is greater that `0.0.0-...`.

Don't know why renovate will suggest `0.14.0` instead of latest `0.14.7` (minor update).

https://www.npmjs.com/package/react?activeTab=versions

**Comment by rarkins** [comment]
For security updates, Renovate will pick the *minimum* version that GitHub's vulnerability alert suggests

**Comment by AdrienLemaire** [comment]
Thanks for the quick reply, and sorry for missing that out in the doc :)

I updated my renovate config as follow, hopefully that'll do the trick
```json
  "packageRules": [
    ...
    {
    "packageNames": ["react", "react-dom"],
    "ignoreUnstable": false,
    "followTag": "experimental"
    }
  ],
```

**Comment by rarkins** [comment]
It's a good setting but vulnerability alerts will still likely override. Needs reproduction to study the alert GitHub generates.
