### ISSUE TITLE
lockFileMaintenance appears to ignore packageRules

### ISSUE THREAD

**Issue by gjvoosten** [renovatebot/config-help#867]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

Yes.

### What would you like to do?

Our [`package.json`](https://github.com/NCI-Agency/anet/blob/candidate/client/package.json#L136-L140) has dependencies:
```
    "leaflet": "1.6.0",
    …
    "leaflet.markercluster": "1.4.1",
```
and our [`renovate.json`](https://github.com/NCI-Agency/anet/blob/candidate/.github/renovate.json#L21-L24) has in its packageRules:
```
    {
      "packageNames": ["draft-js", "leaflet"],
      "enabled": false
    }
```
yet *lockFileMaintenance* insist on [updating leaflet to 1.7.x](https://github.com/NCI-Agency/anet/pull/3184/files#diff-7001a83fec5f94d5b069b9576ead2ff5L10707-R10684) (which is incompatible with leaflet.markercluster).

Is this a problem in our configuration, or a bug in renovate?

**Comment by rarkins** [comment]
lockFileMaintenance is as simple as:
1. Delete lock file
2. Run install
3. Commit new lock file

There is no packageRules logic applicable because in your case it's all done by `yarn`.

Also, neither Renovate nor Yarn are technically updating your direct package.json dependency leaflet from 1.6.0 to 1.7.1. What you're seeing is an optional transitive dependency from here: https://github.com/NCI-Agency/anet/blob/bf43502f668c6af77582e377f66f5f936f04fe1b/client/yarn.lock#L10663

If you add `yarnDedupeFewer` ([docs](https://docs.renovatebot.com/configuration-options/#postupdateoptions)) to your renovate config it may work to keep it at 1.6.0, but that would just be luck. You'd be better to add a [yarn resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) limiting it to your preferred version.

**Comment by gjvoosten** [comment]
Thanks for clearing this up, @rarkins ! Was unaware that lockFileMaintenance was doing just that; indeed fixing it through yarn seems the better solution.
