### ISSUE TITLE
Require onboarding MR/PR even if config exists?

### ISSUE THREAD

**Issue by mxey** [renovatebot/config-help#872]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

We want to explicitly onboard all our repositories because want to verify that repositories have functional pipelines before Renovate creates lots of MRs on them. The problem is that we have a template project that new projects will be based on. We would like Renovate to update that template, therefore we will need a renovate.json in that repository. But if people copy that project (not fork), they will also copy the renovate.json. Since Renovate only needs the config file to exist, even if there is no onboarding MR, the new projects will not go through onboarding. If we remove the renovate.json from the template project, that project will not be updated. If we disable requireConfig, then we cannot close the Renovate MR without enabling Renovate, so we cannot opt-out individual repositories easily.

**Comment by rarkins** [comment]
Sorry, I couldn't think of a solution to this. 

One of the challenges of this would be that the onboarding PR could get *very* old after a while, e.g. you could potentially have 100s or 1000s of merged Renovate PRs and we'd need to fetch all of them in order to include the onboarding one. Either that or potentially a special query but that would require one extra API call per run per repo as the trade-off.

What if you add a special rule just for your template repo? e.g. put its config in your bot config and don't require a config just for that specific repo? That way it will have no renovate.json to be copied into new repos so they'll get onboarding PRs once they're created.

**Comment by mxey** [comment]
@rarkins How can I put repo-specific rules in the config.js? I thought that was not possible.

**Comment by rarkins** [comment]
Are you running with `--autodiscover=true`? If so then I think it's possible using `config.js`,

If so then I think the following works if you add this to your bot's config for the one you don't want a config/onboarding for:

```
    repositories: [{
      repository: 'org/repo',
      onboarding: false,
      requireConfig: false,
      // other config
    }],
```

**Comment by mxey** [comment]
@rarkins Thanks, I'll give that try. The documentation has no details on the `repositories ` option ;)

**Comment by viceice** [comment]
@mxey feel tree to improve the docs after successful config. 🙃 

https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosted-configuration.md#repositories

**Comment by mxey** [comment]
@rarkins Great, that works as intended.

@viceice Except I don't know what configuration is valid there, that was the whole problem ;)
