### ISSUE TITLE
Advice for cutting down email spam?

### ISSUE THREAD

**Issue by robdodson** [renovatebot/config-help#88]
Really enjoying renovate, but because the project I work on is [a monorepo of every major JS framework](https://github.com/webcomponents/custom-elements-everywhere), I am _drowning_ in GitHub emails, haha 😅

I was planning to setup an email filter to delete anything from renovate[bot] with either chore(dep) or fix(dep) in the subject, but I was wondering if there was a better alternative? I have automerge setup so many of these emails really aren't worth reading. But if renovate[bot] ever sends me anything out of the ordinary I want to make sure that still makes it to my inbox. I'm also planning to setup the schedule feature. Any other advice? Thanks!

**Comment by rarkins** [comment]
Unfortunately, the primary cause is GitHub's lack of configurability so we are both a little limited in what we can do.

BTW in case you haven't seen it, I wrote a doc a while ago on "Noise Reduction": https://renovatebot.com/docs/noise-reduction/

One possibility if you are automerging anyway is to do a *branch* automerge. When branch automerging is enabled, Renovate will:

- Create the branch for testing
- If tests fail, raise a PR
- If tests pass, merge the commit to `master`

In the passing case, it should mean you don't get any emails at all. You get a little less "visibility" (no PR was raised) but it sounds like you could do with a little less "visibility" anyway.

Scheduling can indirectly help reduce the noise too. e.g. if you schedule for weekly and some dependencies are on average getting updated 2 times per week, then in theory that reduces the number of PRs for those dependencies by 50%. But still you probably end up with quite a few all coming at once, weekly.

Grouping also helps, especially if combined with scheduling. e.g. maybe you can combine all devDependencies so that you get a combined "Update devDependencies" PR once per week - maybe even per month - instead of individually. Grouping increases the chance that "one bad apple spoils the bunch" though - i.e. the PR fails even though 90% of the dependency updates are good.

Perhaps one question is: what would your end user's expectations be for update frequency, and not update more frequently than that. Then group as much as possible, and finally defer to branch automerging whenever possible. 

A final point: PR titles/bodies are pretty customisable (they're just handlebars templates that are overridable) so in theory if you can identify in advance of time which Renovate PRs are "important" or not for you, perhaps we can add a suffix for the rest so you can have an easy email rule. e.g. I've been meaning to add text to PRs that says something like "This PR will be automerged if tests pass" so then you could add an email rule to delete any with that text so you're only alerted to non-automerge ones, or ones with test failures.

**Comment by robdodson** [comment]
Thanks I'll read through the noise reduction post.

Would definitely love the "This PR will be automerged" message. I initially looked at the config to see if that was one of the options.

Branch automerging also sounds really useful, I'll look into that.

How do you go about creating a group all devDependencies rule?

**Comment by rarkins** [comment]
To group all devDependencies together, and with a weekly schedule:

```json
  "packageRules": [
	{
		"depTypeList": ["devDependencies"],
		"schedule": "before 3am on Monday",
		"groupName": "all devDependencies"
	}
  ]
```

Configure your [timezone](https://renovatebot.com/docs/configuration-options/#timezone) at the top level of your config if you want times to be specific to your time zone instead of to UTC.

The value for `groupName` can be anything you want. Right now the PR will look like "Update all devDependencies" if you leave it as suggested.
