### ISSUE TITLE
Dashboard should mention which file the pending PR would update

### ISSUE THREAD

**Issue by valentijnscholten** [renovatebot/config-help#886]
I have a repository with multiple files that get scanned for dependencies and updates:
- package.json
- package-lock.json
- yarn.lock
- requirements.txt
- setup.py
- Dockerfile.nginx
- Dockerfile.django
- Dockerfile.xxxx
- Dockerfile.yyy
- ....
- docker-compose.yml
- docker-compose-override-dev.yml
- docker-compose-override-unittests.yml
- docker-compose-override-xxx.yml
- ....

Renovate seems to detect most of them and list all pending updates in the dashboard. But the dashboard doesn't show where it found the outdated version. 

To be able to decide on approval of the update, I would like to see which file(s) would be affected by the update.

![image](https://user-images.githubusercontent.com/4426050/94373683-52c56880-0107-11eb-8e7c-9e94fc36ac58.png)

**Comment by rarkins** [comment]
The challenge is:
- If you have not many package files then you won't need the feature
- If you have many package files, then it risks being a huge mess with too-long sentences

If you can mock up how you think it should lock (e.g. by editing the markdown in a dummy repo to demonstrate) then we can consider it as a feature request.

If you want to see the from version in the Dashboard, the best way is to update the commit message and PR title itself, so that it's present everywhere.

To do this, update [commitMessageExtra](https://docs.renovatebot.com/configuration-options/#commitmessageextra) from its default (which only shows to version). Search this repo's closed issues for the term and you can find some examples

**Comment by valentijnscholten** [comment]
Understood. What about making sections: 
![image](https://user-images.githubusercontent.com/4426050/94484103-334c3f80-01dc-11eb-9f5e-3e74d2f1ef29.png)

**Comment by rarkins** [comment]
The problem is that it's very common to have multiple package files per PR. And we already have maybe 8 categories/statuses (e.g. pending approval, pending status checks,ignored, etc - it would result in a noisy matrix for most repos if further broke down by file.

Long term I think the best we can do is make this issue more template-able so that you can use handlebars to divide it how you'd like, but that's a while away.

**Comment by valentijnscholten** [comment]
I configured the {{commitMessageExtra}} and {{commitMessageSuffix}} to achieve more or less what we want:

![image](https://user-images.githubusercontent.com/4426050/94672436-8e358200-0315-11eb-987d-f1a5214d90af.png)

But it seems that {{commitMessageExtra}} is not picked up for {{docker-compose}} dependency updates. the {{suffix}}, {{prefix}} and {{topic}} variables are working with {{docker-compose}} updates.

**Comment by rarkins** [comment]
A small hack, but can you try putting these inside `packageRules`?

```json
{
  "extends": [
    "config:base"
  ],
  "dependencyDashboardApproval": true,
  "ignorePaths": ["setup.py", "requirements.txt", "components/package.json", "components/package-lock.json", "dojo/components/yarn.lock", "dojo/components/package.json", "Dockerfile**"],
  "packageRules": [{
    "packageNames": ["*"],
    "commitMessageExtra": "from {{currentVersion}} to {{#if isMajor}}v{{{newMajor}}}{{else}}{{#if isSingleVersion}}v{{{toVersion}}}{{else}}{{{newValue}}}{{/if}}{{/if}}",
    "commitMessageSuffix": "({{packageFile}})"
  }],
  "recreateClosed": true
}
```

**Comment by valentijnscholten** [comment]
I copy-pasted that config, but now it has changed back all the titles to the old / original format :-)

![image](https://user-images.githubusercontent.com/4426050/94684449-613e9a80-0328-11eb-81ce-575f1fa47bd5.png)

![image](https://user-images.githubusercontent.com/4426050/94684527-774c5b00-0328-11eb-8ac4-94c40fbfda4d.png)

**Comment by rarkins** [comment]
Sorry, silly mistake from me. Should be `packagePatterns`, not `packageNames`:

```
{
  "extends": [
    "config:base"
  ],
  "dependencyDashboardApproval": true,
  "ignorePaths": ["setup.py", "requirements.txt", "components/package.json", "components/package-lock.json", "dojo/components/yarn.lock", "dojo/components/package.json", "Dockerfile**"],
  "packageRules": [{
    "packagePatterns": ["*"],
    "commitMessageExtra": "from {{currentVersion}} to {{#if isMajor}}v{{{newMajor}}}{{else}}{{#if isSingleVersion}}v{{{toVersion}}}{{else}}{{{newValue}}}{{/if}}{{/if}}",
    "commitMessageSuffix": "({{packageFile}})"
  }],
  "recreateClosed": true
}
```


Tested: https://github.com/renovate-tests/npm41/issues/1

**Comment by valentijnscholten** [comment]
Profit! Thanks

![image](https://user-images.githubusercontent.com/4426050/94703398-0fedd580-033f-11eb-8b7e-bf9c790a2f6a.png)
