### ISSUE TITLE
How to not group all lockFileMaintenance updates together?

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/config-help#89]
Currently, when doing lockfile maintenance, one PR updates all package-lock.json files in the repo. I would like them to be separate PRs instead, so I can test the important projects quickly, while delaying merge of the other. Is that possible?

**Comment by rarkins** [comment]
To be in separate PRs means they need to have separate branch names. To have separate branch names would mean we need it to be something like `'renovate/' + id + 'lock-file-maintenance'`. I can't think of any easy way to do that right now except statically provisioning a different `branchPrefix` per-package file. How many different branches/PRs would you want?

**Comment by felixfbecker** [comment]
Right now, it's 4.

Could I define the branch name as something like `renovate/lock-file-maintenance/{{path}}`?

**Comment by rarkins** [comment]
@felixfbecker Sorry, after trying this myself I realised/remembered that lock file maintenance has a different logic that makes this harder than I first thought. I will have to refactor a little code this week so that package files can be separated. Feel free to raise it as a feature request in main repo is you prefer, otherwise I'll update here when done.

In short: normally every update required is its own "update" object including its package file, dependency name, etc - and then we group them by branch. For lock file maintenance, we jump straight to the combined "group" without making every file their own "update" first.

**Comment by felixfbecker** [comment]
What setting would I have to use to just exclude all but one package from the lockfile PRs for now?

**Comment by rarkins** [comment]
Sorry, only way I can think of is to disable that package file completely for now. The logic is [hardcoded](https://github.com/renovatebot/renovate/blob/d0ec341e15d5beafcf962599e0f88ee3b17460cf/lib/manager/npm/post-update/index.js#L29) and I couldn't work out a way to easily undo that without needing to touch 5+ files. I'll see tomorrow if I can get a stable refactoring so that `packageRules.paths` can be applied.

**Comment by rarkins** [comment]
@felixfbecker I made the refactor yesterday and it should hopefully satisfy your requirements.

Here is how to separate each lock file maintenance into a separate PR, as you originally asked:

```
    "lockFileMaintenance": {
      "enabled": true,
      "branchTopic": "lock-file-maintenance-{{packageFile}}",
      "commitMessageExtra": "({{packageFile}})"
}
```

Example PR list:
![image](https://user-images.githubusercontent.com/6311784/45250193-6b9b2f80-b32e-11e8-9139-2a51a64a8ff5.png)

Example PR:
![image](https://user-images.githubusercontent.com/6311784/45250198-7fdf2c80-b32e-11e8-84d3-cd07c6eb2781.png)
