### ISSUE TITLE
Differentiate schedule for branch push and MR creation 

### ISSUE THREAD

**Issue by bydga** [renovatebot/config-help#910]
### Which Renovate are you using?

Renovate Open Source CLI
### Which platform are you using?
GitLab self-hosted
### What would you like to do?
Hi, is there a possibility to have different schedule for branch creation and MRs being created (with `prCreation: not-pending`) I.e. we have a lot of repositories we want to check - It would be great if the branches could have been pushed "at every time" (limited only by the`prCommitsPerRunLimit` so we won't overwhelm the CI server (branch push triggeres a gitlab pipeline), but the MRs will be created only i.e. weekends only - so we don't disturb the developers too often?

When I set the schedule and i am outside the window, Renovate doesn't do anything with message `Skipping branch creation as not within schedule`

**Comment by rarkins** [comment]
We don't currently have planned any capability for *multiple* schedules, but I think https://github.com/renovatebot/renovate/issues/4866 would work for you anyway because it seems like you don't really want a schedule for commits - just MRs. So once that feature is landed, we could make sure that branch-creation is something you can configure to be outside of schedule.

**Comment by bydga** [comment]
Yes, that would work for me 🙂 Thanks for the info, i will watch that issue
