### ISSUE TITLE
What's the proper way to change how different commits are categorized semantically?

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/config-help#93]
Currently, in the base config for my org, we have set:

```
      "patch": {
        "labels": [
          "patch",
          "automerge",
          "dependency-update"
        ]
      },
      "minor": {
        "labels": [
          "minor",
          "dependency-update"
        ],
        "semanticCommitType": "feat",
        "automerge": false
      },
      "major": {
        "labels": [
          "major",
          "dependency-update"
        ],
        "semanticCommitType": "feat",
        "commitBody": "BREAKING CHANGE:",
        "automerge": false
      },
```

However, it seems that the `semanticCommitType` is not getting picked up and I'm still seeing `minor` versions get tagged as `fix`. I'd like them to be tagged as `feat`. I also haven't seen any majors pick up the body change etc. Is there a way to do this that I'm not understanding from the docs?

**Comment by rarkins** [comment]
Are you extending “config:base”? Because it includes an opinionated preset for semantic commit prefixes. I recommend removing the extended if so and just taking the rules you need from it.

**Comment by Aghassi** [comment]
@rarkins 

Currently the extends is 

```
      "extends": [
        "config:js-app",
        ":automergeDigest",
        ":automergePatch"
      ],
```

**Comment by rarkins** [comment]
`config:js-app` extends `config:base`, which includes the rule `:semanticPrefixFixDepsChoreOthers`. That rule is here: https://renovatebot.com/docs/presets-default/#semanticprefixfixdepschoreothers

```
{
  "packageRules": [
    {
      "packagePatterns": [
        "*"
      ],
      "semanticCommitType": "chore"
    },
    {
      "depTypeList": [
        "dependencies"
      ],
      "semanticCommitType": "fix"
    }
  ]
}
```

I suggest you replace `config:js-app` with these instead:
```
    ":ignoreModulesAndTests",
    ":prHourlyLimit2",
    ":prConcurrentLimit20",
    "group:monorepos",
	":pinAllExceptPeerDependencies"
```

The ones I've left out are either (a) same as current default values anyway so do nothing, or (b) the `semanticCommitType` rule you don't want.

**Comment by Aghassi** [comment]
Thanks @rarkins that solved the issue. It was not immediatly obvious that I was not able to override the default settings that I was extending. Is that intended to work that way?

**Comment by rarkins** [comment]
It's a bit of an unsolved problem or "complexity" that I'm thinking how to address. The problem is that Renovate's config works both in terms of sequence as well as specificity, a  little like CSS (which can also be confusing mess at times). So for example `major`/`minor` configuration objects are more specific than the top level, so they would override the top level. But also, `packageRules` are checked last, so they can sometimes override settings like has been done here. Technically JSON objects are not ordered, so it's a little risky for us to extract ordering from them.

Another way to address it would be if there was a nice GUI to interactively browse a "full" config and see how rules are applied, but it's not too simple because they're applied in multiple locations in the code.
