### ISSUE TITLE
Is there a way to group dependencies updates in a single pr while also keeping individual PRs?

### ISSUE THREAD

**Issue by GabrielDuarteM** [renovatebot/config-help#95]
My use case: I use [semantic-release](https://github.com/semantic-release/semantic-release) to automatically release to `npm` a version every time there is a commit starting with `fix` (among other prefixes).

Thing is, every time there is a new version of a dependency (not a devDependency), `renovate` will make a pr starting with `fix`, which in my opinion is good because a new version is released with that update. The only problem is when there are more than one of those PRs. If I have 5 PRs with dependencies upgrades, and I merge them, `semantic-release` will release 5 versions, each containing a single update.

My question: Is there a way to tell renovate to create a new pr containing all the dep upgrades (in addition to the individual ones)? I still think the individual ones are important to see if anything on a build breaks, and to pinpoint what broke more easily, but I would only merge the grouped one, to release a single version...

Unfortunately, I'm having to do this manually, cloning master and manually creating a commit with all the dependencies updated, so I can keep the release changelog clean...

**Comment by rarkins** [comment]
Right now there isn't a way to have *both* individual PRs plus a group at the same time. Maybe a compromise for now is:

- Group together all patch and minor updates into a single (combined) PR, because these should usually pass
- Split any major updates into separate PRs

If this feature existed as you described, would you want it to combine only non-major updates anyway?

**Comment by GabrielDuarteM** [comment]
Your suggestion would definitely help, but then if there is a broken PR, I would have no obvious way to determine which one of the dependency is the culprit. That's why I think it would be important to keep the individual ones, along with the grouped one.

In my use case, if I could keep the individual PRs, it would be better to combine everything (including majors) in a single PR. That way, if every individual PR is passing (which is more often, at least in my case), I could just merge the whole PR.
If it happens to have a PR with a problem, then I would go back to manually do it.

But that's my use case, if the non-major got separated in a different PR, I wouldn't mind too...

**Comment by rarkins** [comment]
Please raise it as a feature request in the main repo. Give as much details as possible, so that others may understand how you think it would work and +1 it if they would like it too. After that it will be prioritised as a feature based on a combination of demand + complexity, and this issue can be closed.

**Comment by Marsup** [comment]
Hi! Was this ever discussed in the main repo? I couldn't find any other issue related to this.

**Comment by rarkins** [comment]
I don’t recall one. Please feel free to add
