### ISSUE TITLE
Help on closing immortal LockFileMaintenance PR

### ISSUE THREAD

**Issue by mohan78** [renovatebot/config-help#952]
### Which Renovate are you using?
Renovate Pro

Other (please write below)

### Which platform are you using?
GitHub Enterprise

### What would you like to do?
Issue: We have enabled renovate on our app and it has generated LockFileMaintenance along with some major releases. For testing purpose, I have created a separate branch other than default one and merged these renovate PRs into that. But the problem is LockFileMaintenance PR is generating again. Is there any way to close it despite of being immortal?

**Comment by rarkins** [comment]
If you want to merge Renovate PRs into a non-default branch then configure Renovate that way instead of re-targetting PRs.

e.g. `"baseBranches": ["dev"]`

(but make sure that your `renovate.json` remains in the default branch)

lockFileMaintenance branches will only be created when they are within schedule, which defaults to Monday mornings. Assuming you didn't change the schedule to any time, it sounds like you forgot to delete the source branch after merging it. Delete the source branch after merge to prevent the branch being reused for a new PR.
