### ISSUE TITLE
PR title suffix question

### ISSUE THREAD

**Issue by wyardley** [renovatebot/config-help#979]
### Which Renovate are you using?
Self-hosted Renovate Pro (latest)

### Which platform are you using?
GitHub Enterprise

### What would you like to do?
I'm wondering if there's a way to tweak the config such that the commit message and PR title matches in a case like:

`[chore] Update xyz to v3.47.0 (minor)`

where the commit has all of this except the "(minor)".

This is separate from https://docs.renovatebot.com/configuration-options/#commitmessagesuffix, right (since it's showing up in the title, but _not_ the commit message)?

Also, will editing it screw up Renovate?

We have a specific use case where we have a check that the PR title and commit message match.

**Comment by rarkins** [comment]
The logic for adding this information to PR titles is unfortunately non-configurable:

```
    if (upgrade.isGroup) {
      upgrade.prTitle +=
        upgrade.updateType === 'major' && upgrade.separateMajorMinor
          ? ' (major)'
          : '';
      upgrade.prTitle +=
        upgrade.updateType === 'minor' && upgrade.separateMinorPatch
          ? ' (minor)'
          : '';
      upgrade.prTitle += upgrade.updateType === 'patch' ? ' (patch)' : '';
    }
```

I can't see a problem if this logic was moved to the commit message too though, so that it's consistent between both.

If you force-push to a Renovate commit to update the message and you reuse the same author, Renovate will itself force-push over it *the next time it needs to rebase*.

If you force-push to a Renovate commit and change the author, then Renovate should flag the branch as modified and *not* commit over the top anymore.

If you edit a PR title, Renovate will revert your changes on the very next run.

**Comment by wyardley** [comment]
Thanks, yeah — noticed that it overwrote the title. The title is a bit too long with it, so may just have to do what we’ve been doing and edit it right before merge vs updating the commit in the branch.

The info about being able to edit the commit message may come in handy for something else, though.
