### ISSUE TITLE
Help onboarding bazelbuild/bazel-watcher

### ISSUE THREAD

**Issue by achew22** [renovatebot/config-help#99]
https://github.com/bazelbuild/bazel-watcher

I believe I have successfully configured renovatebot but I never received the configuration PR. Are there any steps I might have missed in the setup or are there any log entries that I need to address?

Thanks so much!

**Comment by rarkins** [comment]
@achew22 	I checked the logs and it's installed fine. The issue seems to be that it's not detecting your bazel dependencies so then ignores the repository due to "no package files found". Hopefully it just requires a tweaking of the regex rules we have for detecting bazel dependencies so I'll try to fix that quickly and let you know here if it should be good to go or needs any refactoring of the definitions files first.

**Comment by rarkins** [comment]
@achew22 I've taken a look and worked out what are the "new" syntaxes that Renovate needs to support.

First difference is the use of "urls", as currently we only support "url". Can you confirm if the following logic is OK?

1. Check if any of the urls points to a GitHub repo
2. Check if that GitHub repo contains a newer release
3. If so, update X.tar.gz in all URLs to match newer release Y.tar.gz

Another difference is that previously we were matching against releases/download/X.tar.gz on GitHub, but yours point to archive/X.tar.gz. Are both valid? Is either "preferred"?

**Comment by achew22** [comment]
First, apologies for the churn and thank you for your help! Bazel is still stabilizing, but it is genuinely landing in a better place.

> First difference is the use of "urls", as currently we only support "url". Can you confirm if the following logic is OK?

The switch to `urls` was to support mirror repos so that if you depend on a binary and Github is blocked in the nation that you reside you should still be able to use the library.

I believe your state machine to be correct. I would add an additional step. For Github urls that begin with `https://github.com/bazelbuild/` you can add an additional entry in URLs to `https://mirror.bazel.build/github.com/bazelbuild`. I believe all the bazelbuild repos are mirrored there by a cronjob.

> Another difference is that previously we were matching against releases/download/X.tar.gz on GitHub, but yours point to archive/X.tar.gz. Are both valid? Is either "preferred"?

I believe the difference between `archive` and `releases/download` is that in `archive` you can target a particular commit while `releases/download` you are only able to target tagged releases.

It is anomalous that I'm depending on [bazel-integration-testing](https://github.com/bazelbuild/bazel-integration-testing) at a particular commit, but that's only because the project doesn't yet tag releases. For the purposes of renovatebot, it seems to me a prudent choice to only focus on tagged releases at the expense of not all dependencies working. It would be mildly annoying to get a PR every time any downstream dependency committed to their mainline repo and it would be too risky IMO to automatically commit the change.

WDYT?

**Comment by rarkins** [comment]
Renovate has got better at commits and hashes since I first added bazel support so when looking at your file just now I was thinking that in theory we could keep nearly all the various types of defences updated.

As you note, it would be disruptive to get a non stop flow of such updates, but on the other hand it usually just leads to software decay if you have no automated way to keep updated either. 

The solution can simply be scheduling, eg you could configure Renovate to update immediately when there’s a tagged version release update, and only update commit references weekly or monthly.  You can also group them together although that increases the chance that one update breaks the PR for the rest of them and it may even be difficult to work out which caused it.

**Comment by rarkins** [comment]
Weekly batching already exists

**Comment by rarkins** [comment]
Closing in favour of https://github.com/renovatebot/renovate/issues/2576
